### ISSUE TITLE
arquillian + omnifaces issue

### ISSUE THREAD

**Issue by hpfreire** [omnifaces/omnifaces#136]
I can't get arquillian + omnifaces to work. 
If I remove the omnifaces dependency from my project my test runs succcessfully but if I add the omnifaces dependency I get the following stacktrace on the server startup: (I'm using omnifaces 2.0 and wildfly 8.1)

ERROR [org.jboss.msc.service.fail] MSC000001: Failed to start service jboss.deployment.unit."68dcec30-3c91-4af7-86c0-502af4014056.war".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."68dcec30-3c91-4af7-86c0-502af4014056.war".INSTALL: JBAS018733: Failed to process phase INSTALL of deployment "68dcec30-3c91-4af7-86c0-502af4014056.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_11]
Caused by: java.util.ServiceConfigurationError: javax.servlet.ServletContainerInitializer: Provider org.omnifaces.ApplicationInitializer not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239) [rt.jar:1.8.0_11]
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) [rt.jar:1.8.0_11]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) [rt.jar:1.8.0_11]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) [rt.jar:1.8.0_11]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) [rt.jar:1.8.0_11]
	at org.wildfly.extension.undertow.deployment.ServletContainerInitializerDeploymentProcessor.deploy(ServletContainerInitializerDeploymentProcessor.java:112)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]
	... 5 more

**Comment by NagyGa1** [comment]
The initial exception is probably in the bottom of the stacktrace, so if you wish to get a reply might want to elaborate on that "... 5 more" part.

**Comment by BalusC** [comment]
This is more of Arquillian problem than OmniFaces problem.

Similar Q&A has been posted before: http://stackoverflow.com/questions/30811971/java-util-serviceconfigurationerror-when-running-tests-using-arquillianomniface It may be helpful, otherwise consider asking a question to Arquillian community.
