### ISSUE TITLE
Omnifaces in wildfly as a module

### ISSUE THREAD

**Issue by mromerocodimatix** [omnifaces/omnifaces#145]
Hello,

I'm trying to put the omnifaces jar as a module of wildfly 8.2 so all the apps deployed in the server can used it without have to to the omnifaces jar inside of each war.

Everything is working but when I try to use the validator I'm getting this message:

SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-9) JSF1068: Cannot instantiate component with component-type org.omnifaces.component.validator.ValidateEqual

ERROR [io.undertow.request] (default task-9) UT005023: Exception handling request to xxxxx.xhtml: javax.servlet.ServletException: Expression Error: Named Object: org.omnifaces.component.validator.ValidateEqual not found.
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205) [rewrite-servlet-2.0.12.Final.jar:2.0.12.Final]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]

any idea?

**Comment by BalusC** [comment]
OmniFaces is designed as a web fragment library. It belongs in /WEB-INF/lib and not elsewhere.

Reason for this is thus among others autodiscovery of /META-INF/web-fragment.xml and /META-INF/faces-config.xml as required by annotation scanners.
