### ISSUE TITLE
org.jboss.weld.exceptions.AmbiguousResolutionException between [class org.omnifaces.cdi.converter.ConverterManager]

### ISSUE THREAD

**Issue by jansohn** [omnifaces/omnifaces#163]
I'm not able to get Omnifaces v2.1 running with an embedded Jetty server. The exception I'm receiving:

    Caused by: org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001318: Cannot resolve an ambiguous dependency between: 
      - Managed Bean [class org.omnifaces.cdi.converter.ConverterManager] with qualifiers [@Any @Default],
      - Managed Bean [class org.omnifaces.cdi.converter.ConverterManager] with qualifiers [@Any @Default]
    	at org.jboss.weld.manager.BeanManagerImpl.resolve(BeanManagerImpl.java:1235) ~[weld-servlet-2.3.0.CR2.jar:2015-09-02 06:04]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    	at org.omnifaces.config.BeanManager.getReference(BeanManager.java:143) ~[omnifaces-2.1.jar:2.1]
		[...]

My setup: JDK1.8.0_51, Jetty 9.3.2.v20150730, WELD-2.3.0.CR2, Mojarra 2.2.12, Omnifaces 2.1

My code runs fine when I switch back to Omnifaces 1.x.

Here's the code I use to start the embedded Jetty server:

```java
jettyServer = new Server(8080);

//Enable parsing of jndi-related parts of web.xml and jetty-env.xml
ClassList classlist = ClassList.setServerDefault(jettyServer);
classlist.addAfter("org.eclipse.jetty.webapp.FragmentConfiguration", "org.eclipse.jetty.plus.webapp.EnvConfiguration", "org.eclipse.jetty.plus.webapp.PlusConfiguration", "org.eclipse.jetty.annotations.AnnotationConfiguration");

WebAppContext context = new WebAppContext();

String webappDir = "target/testwebapp-1.0.0/";
context.setResourceBase(webappDir);
context.setDescriptor("src/test/resources/WEB-INF/web.xml");
context.setContextPath("/webapp");		
context.setParentLoaderPriority(true);
context.addEventListener(new Listener()); // add WELD listener

jettyServer.setHandler(context);
jettyServer.start();
jettyServer.dump(System.err);

while (!jettyServer.isStarted())
{
	try { Thread.sleep(500); } catch (InterruptedException e) { log.error(e.getMessage(), e); }
}
```

**Comment by jansohn** [comment]
Minimal webapp to reproduce: https://github.com/jansohn/jetty-omnifaces

Run as 'mvn clean verify' and the test case should succeed. Change Omnifaces dependency to 2.1 and rerun. Now the test case fails with said exception.

**Comment by jansohn** [comment]
Found a solution at https://github.com/jetty-project/embedded-jetty-jsp. Had to remove the line

```java
context.setParentLoaderPriority(true);
```

and replace it with

```java
context.setClassLoader(new URLClassLoader(new URL[0], BaseIntegrationTestClass.class.getClassLoader()));
```
