### ISSUE TITLE
@Eager @ApplicationScoped fails in Tomcat + OWB 1.6.2

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#195]
```
Jan 13, 2016 12:29:42 PM org.omnifaces.cdi.eager.EagerBeansRepository instantiateApplicationScopedAndRegisterListener
WARNING: Could not instantiate eager application scoped beans. Possibly the CDI application scope is not active. This is known to be the case in certain Tomcat and Jetty based configurations.
java.lang.UnsupportedOperationException: java.lang.reflect.InvocationTargetException
	at org.omnifaces.config.BeanManager.getReference(BeanManager.java:154)
	at org.omnifaces.cdi.eager.EagerBeansRepository.getInstance(EagerBeansRepository.java:61)
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateApplicationScopedAndRegisterListener(EagerBeansRepository.java:69)
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:62)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.omnifaces.config.BeanManager.getReference(BeanManager.java:143)
	... 12 more
Caused by: java.lang.IllegalStateException: It's not allowed to call getBeans(Type, Annotation...) before AfterBeanDiscovery
	at org.apache.webbeans.container.InjectableBeanManager.checkAfterBeanDiscoveryProcessed(InjectableBeanManager.java:402)
	at org.apache.webbeans.container.InjectableBeanManager.getBeans(InjectableBeanManager.java:121)
	... 17 more
```

As hinted by root cause, try hooking to `AfterBeanDiscovery` instead.

**Comment by BalusC** [comment]
Looks like initialization ordering problem. This all works just fine in TomEE 7.0.0 M1.

**Comment by BalusC** [comment]
My mistake, I forgot 

```
<listener>
    <listener-class>org.apache.webbeans.servlet.WebBeansConfigurationListener</listener-class>
</listener>
```
