### ISSUE TITLE
Failed to deploy in latest Snapshot build 29-02-2016

### ISSUE THREAD

**Issue by haghar** [omnifaces/omnifaces#215]
I'm currently testing the snapshot build in a webapp and the latest build is throwing an exception when launching with Wildfly 9.0.2:

```
[ERROR] Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 3 exceptions:
[ERROR] Exception 0 :
[ERROR] org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type SocketSessionManager with qualifiers @Default
[ERROR] at injection point [BackedAnnotatedField] @Inject private org.omnifaces.cdi.push.SocketChannelManager.manager
[ERROR] at org.omnifaces.cdi.push.SocketChannelManager.manager(SocketChannelManager.java:0)
[ERROR] Possible dependencies:
[ERROR] - Managed Bean [class org.omnifaces.cdi.push.SocketSessionManager] with qualifiers [@Any @Default],
[ERROR] - Managed Bean [class org.omnifaces.cdi.push.SocketSessionManager] with qualifiers [@Any @Default]
[ERROR] 
[ERROR] at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:367)
[ERROR] at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
[ERROR] at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
[ERROR] at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
[ERROR] at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
[ERROR] at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
[ERROR] at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
[ERROR] at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
[ERROR] at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] at java.lang.Thread.run(Thread.java:745)

```

Thanks

**Comment by BalusC** [comment]
Can't reproduce it in WildFly 9.0.2.Final (nor 8.2.1 and 10.0.0). Exception suggests duplicate OmniFaces JAR files in runtime classpath. There should be at most one in WAR's /WEB-INF/lib. Have you verified the build?

**Comment by BalusC** [comment]
On the other hand, if you have played around with previous 2.3 snapshot versions on the same server as well, clean server's standalone/data, deployments and tmp folders to be sure.

**Comment by haghar** [comment]
This is really weird it happened even after cleaning the server because I deploy with maven, but is not happening anymore sorry for the inconvenience and the time I made you spend time in this pointless question. Maybe something went wrong in the compilation process in maven.

Thanks for your support.

**Comment by BalusC** [comment]
No problem. Keep reporting, one time it might be our fault ;)
