### ISSUE TITLE
Numbers#formatThousandsUnit throws NumberFormatException

### ISSUE THREAD

**Issue by p-kp** [omnifaces/omnifaces#255]
Omnifaces Snapshot 2.4 (From 21.05.2016)

Following expression throws a NumberFormatException with locale set to 'DE_de':

`#{of:formatThousandsUnit(42438, 'm')}`

Stacktrace:

Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:494)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at org.omnifaces.el.functions.Numbers.formatBaseUnit(Numbers.java:247)
	at org.omnifaces.el.functions.Numbers.formatThousandsUnit(Numbers.java:219)

**Comment by BalusC** [comment]
That was an oversight during fixing #252. Thank you for testing and reporting!

Fix is available in today's latest [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).
