### ISSUE TITLE
@Inject @Param can't use in setter and getter 

### ISSUE THREAD

**Issue by cooper-lyt** [omnifaces/omnifaces#275]
```
@Inject @Param
public void setParamValueTest(String value){
 ...
} 

public String getParamValueTest(){
  ....
}
```
cdi procedure inject conflicts?

**Comment by BalusC** [comment]
For the record, below exception is thrown on Tomcat 8.5.3 + Mojarra 2.2.13 + Weld 2.3.4.
```
SEVERE: Exception starting Context with name [/playground-tomcat-weld]
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/playground-tomcat-weld]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3771)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:293)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5534)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1378)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1378)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1346)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedMethod] @Inject @Param public com.example.Bean.setParamValueTest(String)
  at com.example.Bean.setParamValueTest(Bean.java:37)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Producer Method [String] with qualifiers [@Cookie @Any] declared as [[BackedAnnotatedMethod] @Produces @Cookie public org.omnifaces.cdi.cookie.RequestCookieProducer.produce(InjectionPoint)],
  - Producer Method [String] with qualifiers [@ContextParam @Any] declared as [[BackedAnnotatedMethod] @Produces @ContextParam public org.omnifaces.cdi.contextparam.ContextParamProducer.produce(InjectionPoint)]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
```

**Comment by BalusC** [comment]
It appears that `ParamExtension` needs to be altered to take into account annotated setters. Currently, it only supports annotated fields. 

Injection in setters is considered poor practice. Is there a particular technical reason in your specific case?

**Comment by cooper-lyt** [comment]
I have a Base class:

```
public abstract class EntityHome{

private String id;

public String getId(){
.....
}

public void setId(String id){
.....
}
}
```
children class from request param get ID

**Comment by BalusC** [comment]
It looks like you're tight coupling frontend model with backend model. You shouldn't have frontend specific dependencies in backend classes. I.e. JPA entities and EJB services should nowhere have `import javax.faces.xxx` or `import org.omnifaces.xxx`, etc which import classes from frontend. Otherwise, your backend classes are not reusable on different frontends such as JAX-RS, JSP/Servlet, etc. The `@Param` annotation is intented to be used on a field of a real managed bean, not an entity.

Sorry, I'd rather not encourage poor practices. Closing off as WONTFIX.
