### ISSUE TITLE
EagerBeansPhaseListener.afterPhase throws NullPointerException in multi module EAR

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#290]
http://stackoverflow.com/q/38594094/157882
```
java.lang.NullPointerException
    at org.omnifaces.cdi.eager.EagerBeansPhaseListener.afterPhase(EagerBeansPhaseListener.java:50)
    at com.sun.faces.lifecycle.Phase.handleAfterPhase(Phase.java:189)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:107)
    at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:121)
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
 ```

**Comment by BalusC** [comment]
Programmtic registration of listeners/filters is not allowed when done by a listener which is itself programmatically registered, so things had to be reverted and reviewed.
