### ISSUE TITLE
CombinedResourceHandler fetchs libraries on ajax requests if page contains c:if since omnifaces 2.4

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#301]
Hi,

I have this simple page:

`<html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:h="http://java.sun.com/jsf/html"
          xmlns:f="http://java.sun.com/jsf/core"
          xmlns:p="http://primefaces.org/ui"
          xmlns:c="http://java.sun.com/jsp/jstl/core">
        <f:view contentType="text/html" locale="#{userSessionBean.locale}"> 
            <h:head>
                <h:outputScript target="head" name="js/myscript.js"/>
            </h:head>
            <h:body>
                <h:form>
                    <h:commandButton value="example">
                        <p:ajax process="@this" update="@this"/>
                    </h:commandButton>
                </h:form>
                <c:if test="false">
                    random
                </c:if>
            </h:body>
        </f:view>
</html>`

And in faces-config.xml:
`       <resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
        <resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>    `

myscript.js is combined and served ok in the GET request. In an ajax request, myscript.js is reloaded, breaking some funcionalities (not in this simple example of course).

This only happens if the page contains c:if and since omnifaces 2.4 (also happens in 2.5-SNAPSHOT)

My environment:
Tomee 7.0.1
Myfaces 2.2.10
Omnifaces 2.4
developmentStage=production

**Comment by BalusC** [comment]
Hmm, possibly caused by #273.

**Comment by cocorossello** [comment]
Also using PF 6.0, I forgot to mention, sorry.

It was working right with PF 6.0 and omnifaces 2.3, although we had [Primefaces 6.0 partial request issue](https://github.com/omnifaces/omnifaces/issues/273) , which I thought it was just a bug in PF 6.0 when making some redirects in ajax calls.

**Comment by BalusC** [comment]
Sorry, I can't reproduce it in TomEE 7.0.1 with a scratchpad project based on the information provided so far. I only removed the <f:view locale> attribute and the rest is just default/documented.

**Comment by cocorossello** [comment]
sorry, I should have provided an example project. Here it is (when packaging tomee is also built, you can run it from target folder)
[example.zip](https://github.com/omnifaces/omnifaces/files/428532/example.zip)

**Comment by BalusC** [comment]
This is not correct:
```
<h:outputScript target="head" name="primefaces/jquery/jquery.js" />
```

Now you have duplicate jQuery libraries included because the PrimeFaces-bundled one is identified by `library="primefaces"` as below

```
<h:outputScript target="head" library="primefaces" name="jquery/jquery.js" />
```
Fix it or just remove it and then retry.

**Comment by BalusC** [comment]
I reproduced it, the incorrect script inclusion wasn't the cause. 

I will look at it later the day. Thanks for the reproducer!

**Comment by cocorossello** [comment]
Hi,

The outputscript was just an example to import a javascript library. In the real application I have a custom head renderer to import some libraries in the desired order:

`@ResourceDependencies({
    @ResourceDependency(library="primefaces-bootstrap", name="theme.css"),
    @ResourceDependency(library="primefaces", name="jquery/jquery.js"),
    @ResourceDependency(library="primefaces", name="jquery/jquery-plugins.js"),
    @ResourceDependency(library="primefaces", name="core.js"),
    @ResourceDependency(library="primefaces", name="components.js"),
    @ResourceDependency(library="primefaces", name="components.css"),    
})
public class HeadRenderer extends Renderer {

    @Override
    public void encodeBegin(FacesContext context, UIComponent component) throws IOException {
        context.getResponseWriter().startElement("head", component);
    }

    @Override
    public void encodeChildren(FacesContext context, UIComponent component) throws IOException {
        // NOOP.
    }

    @Override
    public void encodeEnd(FacesContext context, UIComponent component) throws IOException {
        for (UIComponent resource : context.getViewRoot().getComponentResources(context, "head")) {
            resource.encodeAll(context);
        }

        context.getResponseWriter().endElement("head");
    }

}`

**Comment by BalusC** [comment]
This issue has been fixed in today's latest 2.5-SNAPSHOT.

I will create an IT later which should also cover #273.

**Comment by cocorossello** [comment]
Sorry to disturb you again, but I couldn't get it to work. 

This occurs only in the latest snapshots, I don't know exactly which commit broke it.

If I have an @ApplicationScoped (or @Singleton) like this t
[example.zip](https://github.com/omnifaces/omnifaces/files/430048/example.zip)
he application break:

`@ApplicationScoped
@Named
@Startup
public class MyApplicationScopedBean {
    
    @Inject
    private MyStateless myStateless;
...
    `


It works fine without the inject or without the @Startup or with OF 2.4


Stacktrace:


22-Aug-2016 14:03:23.548 SEVERE [localhost-startStop-1] org.apache.openejb.cdi.OpenEJBLifecycle.startApplication CDI Beans module deployment failed
 org.apache.webbeans.exception.WebBeansDeploymentException: Error while sending SystemEvent to a CDI Extension! org.apache.webbeans.portable.events.discovery.AfterDeploymentValidationImpl@32ace167
	at org.apache.webbeans.event.NotificationManager.fireEvent(NotificationManager.java:697)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:485)
	at org.apache.webbeans.container.BeanManagerImpl.fireLifecycleEvent(BeanManagerImpl.java:480)
	at org.apache.webbeans.config.BeansDeployer.fireAfterDeploymentValidationEvent(BeansDeployer.java:719)
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:314)
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:196)
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:193)
	at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:911)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:717)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1257)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1115)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5076)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:702)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.webbeans.exception.WebBeansException: java.lang.reflect.InvocationTargetException
	at org.apache.webbeans.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:318)
	at org.apache.webbeans.event.NotificationManager.fireEvent(NotificationManager.java:676)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.webbeans.event.ObserverMethodImpl.invoke(ObserverMethodImpl.java:347)
	at org.apache.webbeans.event.ContainerEventObserverMethodImpl.invoke(ContainerEventObserverMethodImpl.java:82)
	at org.apache.webbeans.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:312)
	... 26 more
Caused by: java.lang.IllegalStateException: no interface to proxy for ejb MyStateless, is this is a MDB maybe you shouldn't use a scope?
	at org.apache.openejb.cdi.CdiEjbBean.createEjb(CdiEjbBean.java:252)
	at org.apache.openejb.cdi.CdiPlugin.getSessionBeanProxy(CdiPlugin.java:241)
	at org.apache.webbeans.container.BeanManagerImpl.getEjbOrJmsProxyReference(BeanManagerImpl.java:955)
	at org.apache.webbeans.container.BeanManagerImpl.getReference(BeanManagerImpl.java:781)
	at org.apache.webbeans.container.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:654)
	at org.apache.webbeans.inject.AbstractInjectable.inject(AbstractInjectable.java:103)
	at org.apache.webbeans.inject.InjectableField.doInjection(InjectableField.java:65)
	at org.apache.webbeans.portable.InjectionTargetImpl.injectFields(InjectionTargetImpl.java:220)
	at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:206)
	at org.apache.webbeans.portable.InjectionTargetImpl.inject(InjectionTargetImpl.java:196)
	at org.apache.webbeans.component.AbstractOwbBean.create(AbstractOwbBean.java:126)
	at org.apache.webbeans.component.ManagedBean.create(ManagedBean.java:67)
	at org.apache.webbeans.context.creational.BeanInstanceBag.create(BeanInstanceBag.java:76)
	at org.apache.webbeans.context.AbstractContext.getInstance(AbstractContext.java:159)
	at org.apache.webbeans.context.AbstractContext.get(AbstractContext.java:125)
	at org.apache.webbeans.intercept.NormalScopedBeanInterceptorHandler.getContextualInstance(NormalScopedBeanInterceptorHandler.java:100)
	at org.apache.webbeans.intercept.ApplicationScopedBeanInterceptorHandler.getContextualInstance(ApplicationScopedBeanInterceptorHandler.java:65)
	at org.apache.webbeans.intercept.NormalScopedBeanInterceptorHandler.get(NormalScopedBeanInterceptorHandler.java:70)
	at com.example.MyApplicationScopedBean$$OwbNormalScopeProxy0.toString(com/example/MyApplicationScopedBean.java)
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateBeans(EagerBeansRepository.java:126)
	at org.omnifaces.cdi.eager.EagerBeansRepository.instantiateApplicationScoped(EagerBeansRepository.java:97)
	at org.omnifaces.cdi.eager.EagerBeansRepository.setEagerBeans(EagerBeansRepository.java:74)

**Comment by BalusC** [comment]
This was caused by a recent optimization to `@Eager` which appears to be incorrect after all. I have reverted it. Please retry the current snapshot.

**Comment by cocorossello** [comment]
Tested, it works fine.

Thanks!

**Comment by BalusC** [comment]
Great, thank you for reporting and improving OmniFaces!

**Comment by BalusC** [comment]
FYI: integration test has been added: https://github.com/omnifaces/omnifaces/commit/fd2f6d169534c832b75bd88f92fa0123bbefea1f

The "rebuild" actions simulate JSTL behavior.
