### ISSUE TITLE
omnifaces 2.6.1 cannot be used with java 1.7 

### ISSUE THREAD

**Issue by ravihariharan** [omnifaces/omnifaces#363]
Reference : omnifaces 2.6 cannot be used with java 1.7 #358

Runtime error when migrating from omnifaces-2.5.1.jar to omnifaces-2.6.1.jar on Java 1.7 , apache-tomcat-7.0.75.

`SEVERE: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at org.omnifaces.cdi.push.SocketFacesListener.register(SocketFacesListener.java:119)
	at org.omnifaces.cdi.push.Socket.encodeChildren(Socket.java:730)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)`

`omnifaces-2.6.1.jar
SocketFacesListener
/**
	 * Register given socket and returns true if it's new.
	 */
	static boolean register(FacesContext context, Socket socket) {
		return getSockets(context).putIfAbsent(socket.getClientId(context), socket.isConnected()) == null;
	}
`

![image](https://cloud.githubusercontent.com/assets/15189434/23562531/cd90d294-0010-11e7-80b5-5def2258b25c.png)

**Comment by BalusC** [comment]
Thank you for the report. I'll have to review the project configuration. Eclipse is set to 1.7 and Maven is set to 1.7 and yet 1.8 code gets compiled.

**Comment by BalusC** [comment]
OK, it was Eclipse's fault. Even when using JDK8 runtime with project set to Java 1.7 compliance, it doesn't mark Java 1.8 things as errors somehow. I had to explicitly configure the project to use JDK7.

**Comment by ravihariharan** [comment]
Thanks BalusC. :)
