### ISSUE TITLE
Session timeout not configured in web.xml throws NumberFormatException

### ISSUE THREAD

**Issue by fabiyo** [omnifaces/omnifaces#369]
Using Omnifaces 2.6.1 and no session timeout in web.xml gives the following message:

2017-04-05 09:08:18,805 [DEBUG] org.omnifaces.util.Utils (Utils.java:234) = Ignoring thrown exception; the sole intent is to return false instead.
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at org.omnifaces.util.Utils.isNumber(Utils.java:231)
	at org.omnifaces.config.WebXml.parseSessionTimeout(WebXml.java:525)

Solution: 

1) (not desirable) adding a session timeout in web.xml ... 	`<session-config><session-timeout>1</session-timeout></session-config>`

2) roll back to version 2.5.1 (2.6 same issue)

**Comment by BalusC** [comment]
This is a DEBUG message, not an ERROR.

Since OmniFaces 2.6, all suppressed exceptions are logged. You will see them when the log level is set to DEBUG.

**Comment by fabiyo** [comment]
Agreed, replaced error by message.
