### ISSUE TITLE
@ConversationScoped fails in the OmniFaces 2.6.x.

### ISSUE THREAD

**Issue by ahamana** [omnifaces/omnifaces#376]
When I use FacesViews, @ConversationScoped fails in the OmniFaces 2.6.x.

I read the following the stackoverflow and I understood the workaround in the the OmniFaces 2.5.x.
But the context parameter "org.omnifaces.FACES_VIEWS_VIEW_HANDLER_MODE" is deprecated in the OmniFaces 2.6.x.
http://stackoverflow.com/questions/42039554/conversationscoped-bean-behaves-as-requestscoped-since-omnifaces-2-5-facesview

What is the correct workaournd in the OmniFaces 2.6.x?

[My code]
---
- Java
```
package test;

import java.io.Serializable;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.omnifaces.util.Faces;

@ConversationScoped
@Named
@SuppressWarnings("serial")
public class LoginFlow implements Serializable
{
    @Inject
    private Conversation conversation;

    public void initConversation()
    {
        if ( conversation.isTransient() ) {
            conversation.begin();
        }
    }

    public void login()
    {
        conversation.end();

        // Do something.

        Faces.redirect( "/top" );
    }

    public void cancel()
    {
        conversation.end();

        Faces.redirect( "/index" );
    }
}
```

- Facelets
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:jsf="http://xmlns.jcp.org/jsf"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:o="http://omnifaces.org/ui"
    xml:lang="#{ view.locale.language }" lang="#{ view.locale.language }">
  <f:metadata>
    <f:viewAction action="#{ loginFlow.initConversation() }" />
  </f:metadata>
  <head jsf:id="head">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/lib/css/bootstrap.min.css" />
    <script src="/lib/js/jquery.min.js"></script>
    <script src="/lib/js/bootstrap.min.js"></script>
    <title>Login</title>
  </head>
  <body jsf:id="body">
    <ui:include src="/common/header.xhtml" />
    <div id="content">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="page-header">
              <h3>Login</h3>
            </div>
          </div>
          <div class="col-xs-12 col-sm-8 col-md-6">
            <o:messages id="errors" styleClass="list-unstyled" errorClass="text-danger" />
            <o:highlight />
            <form jsf:id="login-form" jsf:prependId="false">
              <label class="control-label">Email</label>
              <div class="form-group">
                <input jsf:id="email" type="email" class="form-control" jsf:label="Email" />
              </div>
              <label class="control-label">Password</label>
              <div class="form-group">
                <input jsf:id="password" type="password" class="form-control" data-toggle="password" data-message="" jsf:redisplay="#{ facesContext.postback }" jsf:label="Password" />
              </div>
              <div class="btn-toolbar">
                <button jsf:id="cancel" class="btn" jsf:immediate="true" jsf:action="#{ loginFlow.cancel() }">Cancel</button>
                <button jsf:id="login" class="btn btn-primary" jsf:action="#{ loginFlow.login() }">Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <ui:include src="/common/footer.xhtml" />
  </body>
</html>
```

Conversation#end() is called, the following exception is thrown.
javax.faces.FacesException: #{ loginFlow.cancel() }: java.lang.IllegalStateException: WELD-000329: Attempt to call end() on a transient conversation
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:931)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	...

Thank you in advance.

**Comment by BalusC** [comment]
Ignore the deprecation warning. You can keep using the `org.omnifaces.FACES_VIEWS_VIEW_HANDLER_MODE` work around. It's marked deprecated since 2.6 because it's to be removed in 3.0.

**Comment by ahamana** [comment]
I use 2.6.2 but I need this workaround.
