### ISSUE TITLE
ClassCastException using o:param with converter

### ISSUE THREAD

**Issue by svenhaag** [omnifaces/omnifaces#438]
Omnifaces 3.0
JSF 2.3-edr1
Mojarra 2.3.3
PrimeFaces 6.2

Defined a @FacesConverter("my.ConverterId")

<h:button outcome="mmc_organization_edit">
  <o:param value="#{bean.myObject}" converter="my.ConverterId" />
</h:button>

In **another** bean:
@Inject
@Param(converter = "my.ConverterId", name = "urlParamName")
private MyObject myObject;

On button click I get:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class
	at org.omnifaces.cdi.param.ParamProducer.getConverter(ParamProducer.java:292) ~[omnifaces-3.0.jar:3.0]
	at org.omnifaces.cdi.param.ParamProducer.getConvertedValues(ParamProducer.java:138) ~[omnifaces-3.0.jar:3.0]
	at org.omnifaces.cdi.param.ParamProducer.produce(ParamProducer.java:102) ~[omnifaces-3.0.jar:3.0]
	at org.omnifaces.cdi.param.DynamicParamValueProducer.create(DynamicParamValueProducer.java:72) ~[omnifaces-3.0.jar:3.0]

**Comment by BalusC** [comment]
Fixed. Thanks for reporting!
