### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer at org.omnifaces.util.Hacks.removeViewState

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#444]
https://stackoverflow.com/q/49445846/157882

> I'm trying to upgrade myfaces to latest version (without the whole java EE 8 stack, since tomee 8 is still not released).
> 
> It seems to work fine in most of the cases, however refreshing some pages throws this error
> 
> java.lang.ClassCastException: [B cannot be cast to java.base/java.lang.Integer
> at org.omnifaces.util.Hacks.removeViewState(Hacks.java:432)
> at org.omnifaces.viewhandler.OmniViewHandler.unloadView(OmniViewHandler.java:134)
> at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:101)
> at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:97)

**Comment by BalusC** [comment]
Fixed in 2.6.9-SNAPSHOT
