### ISSUE TITLE
Support @ContextParam outside of JSF

### ISSUE THREAD

**Issue by adam-waldenberg** [omnifaces/omnifaces#493]
At the moment, `@ContextParam` uses `facesContext.getExternalContext().getInitParameter(name)` to fetch init parameters from `web.xml`. If no JSF page has been loaded and the FacesContext is not initialized this causes a `NullPointerException`. 

```
Caused by: java.lang.NullPointerException
	at org.omnifaces.util.FacesLocal.getInitParameter(FacesLocal.java:1410)
	at org.omnifaces.util.Faces.getInitParameter(Faces.java:2007)
	at org.omnifaces.cdi.contextparam.ContextParamProducer.produce(ContextParamProducer.java:44)
```

`@ContextParam` should probably use `ServletContext` directly instead, this will allow `@ContextParam` to be used outside of JSF requests.

**Comment by BalusC** [comment]
Fair point. Same applies to `@Cookie`, so I have also adjusted it accordingly. The `@Param` is a bit difficult because it relies on JSF conversion/validation.
