### ISSUE TITLE
Websphere Base 9.0.0.9 o:socket issue

### ISSUE THREAD

**Issue by ravihariharan** [omnifaces/omnifaces#502]
version - omnifaces-2.7.jar 

Using the sample showcase the below code works on tomcat.

When I deploy the application on WAS 9 which support WebSocket the error message is
`You need to set web.xml context param 'org.omnifaces.SOCKET_ENDPOINT_ENABLED' with value 'true'`

Sample : https://github.com/ravihariharan/WasWebSocketTestApp

https://stackoverflow.com/questions/54225556/why-is-omnifaces-websocket-osocket-not-working-with-websphere-9#comment96368602_54225556

`[2/21/19 16:55:39:285 EST] 00000341 XCT           I   END   AAUFDHvrYEo-AAAAAAAAAzQ 00000000000-cccccccccc2 HTTPCF(InboundRequest RC=200 RequestContext(com.ibm.ws.http.channel.inbound.impl.HttpInboundServiceContextImpl@d350240))
[2/21/19 16:55:51:394 EST] 00000341 XCT           I   BEGIN AAUFDHvrYEo-AAAAAAAAAzR 00000000000-cccccccccc2 HTTPCF(InboundRequest /WasWebSocketTestApp/PushBean.xhtml RemoteAddress(10.198.0.5) RequestContext(com.ibm.ws.http.channel.inbound.impl.HttpInboundServiceContextImpl@8cbf9e10))
[2/21/19 16:55:51:441 EST] 00000341 ServletWrappe E com.ibm.ws.webcontainer.servlet.ServletWrapper service SRVE0014E: Uncaught service() exception root cause Faces Servlet: javax.servlet.ServletException: o:socket endpoint is not enabled. You need to set web.xml context param 'org.omnifaces.SOCKET_ENDPOINT_ENABLED' with value 'true'.
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1124)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4217)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.handleRequest(WebAppImpl.java:2208)
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1030)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
Caused by: java.lang.IllegalStateException: o:socket endpoint is not enabled. You need to set web.xml context param 'org.omnifaces.SOCKET_ENDPOINT_ENABLED' with value 'true'.
	at org.omnifaces.cdi.push.Socket.encodeChildren(Socket.java:727)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:119)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	... 25 more
`

**Comment by ravihariharan** [comment]
not sure if it has to something with

It will install the SocketEndpoint. Lazy initialization of the endpoint via component is unfortunately not possible across all containers (yet). See also WS spec issue 211.

the link to WS spec issue 211 does not work

**Comment by ravihariharan** [comment]
WAS 9.0.9 -  com.ibm.ws.jsf.myfaces.jar

com.ibm.ws.jsf.myfaces.jar\META-INF\DEPENDENCIES
`
// ------------------------------------------------------------------
// Transitive dependencies of this project determined from the
// maven pom organized by organization.
// ------------------------------------------------------------------

Apache MyFaces JSF-2.2 Core Impl


From: 'an unknown organization'
  - annotations-api  org.apache.tomcat:annotations-api:jar:6.0.29

  - catalina  org.apache.tomcat:catalina:jar:6.0.29

  - juli  org.apache.tomcat:juli:jar:6.0.29

  - servlet-api  org.apache.tomcat:servlet-api:jar:6.0.29

  - tomcat-annotations-api  org.apache.tomcat:tomcat-annotations-api:jar:7.0.0

  - tomcat-api  org.apache.tomcat:tomcat-api:jar:7.0.0

  - tomcat-catalina  org.apache.tomcat:tomcat-catalina:jar:7.0.0

  - tomcat-juli  org.apache.tomcat:tomcat-juli:jar:7.0.0

  - tomcat-servlet-api  org.apache.tomcat:tomcat-servlet-api:jar:7.0.0

  - tomcat-util  org.apache.tomcat:tomcat-util:jar:7.0.0


From: 'Apache Software Foundation' (http://www.apache.org)
  - EJB 3.0 (http://geronimo.apache.org/specs/geronimo-ejb_3.0_spec) org.apache.geronimo.specs:geronimo-ejb_3.0_spec:jar:1.0.1
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - JPA 1.0 (http://geronimo.apache.org/specs/geronimo-jpa_3.0_spec) org.apache.geronimo.specs:geronimo-jpa_3.0_spec:jar:1.1.1
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)

From: 'Google' (http://www.google.com/)
  - Guice (http://code.google.com/p/google-guice/) com.google.code.guice:guice:pom:1.0
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)

From: 'The Apache Software Foundation' (http://jakarta.apache.org)
  - Codec (http://jakarta.apache.org/commons/codec/) commons-codec:commons-codec:jar:1.3
    License: The Apache Software License, Version 2.0  (/LICENSE.txt)
  - Collections (http://jakarta.apache.org/commons/collections/) commons-collections:commons-collections:jar:3.2
    License: The Apache Software License, Version 2.0  (/LICENSE.txt)
  - Digester (http://jakarta.apache.org/commons/digester/) commons-digester:commons-digester:jar:1.8
    License: The Apache Software License, Version 2.0  (/LICENSE.txt)

From: 'The Apache Software Foundation' (http://www.apache.org)
  - Apache Geronimo JSR-330 Spec API (http://geronimo.apache.org/maven/genesis/1.0) org.apache.geronimo.specs:geronimo-atinject_1.0_spec:bundle:1.0
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - Apache Geronimo JSR-303 Bean Validation Spec API (http://geronimo.apache.org/maven/specs/geronimo-validation_1.0_spec/1.1) org.apache.geronimo.specs:geronimo-validation_1.0_spec:bundle:1.1
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)

From: 'The Apache Software Foundation' (http://www.apache.org/)
  - Commons BeanUtils (http://commons.apache.org/beanutils/) commons-beanutils:commons-beanutils:jar:1.8.3
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - Commons Logging (http://commons.apache.org/logging) commons-logging:commons-logging:jar:1.1.1
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - Apache MyFaces JSF-2.2 Core API (http://myfaces.apache.org/core21/myfaces-api) org.apache.myfaces.core:myfaces-api:jar:2.2.8
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - Apache MyFaces Core For JSF 2.2 - Shared (http://myfaces.apache.org/core22/myfaces-impl-shared) org.apache.myfaces.core.internal:myfaces-impl-shared:jar:2.2.8
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
  - Apache MyFaces Shared Public API For JSF 2.2 - Core (http://myfaces.apache.org/core22/myfaces-impl-shared-public) org.apache.myfaces.core.internal:myfaces-impl-shared-public:jar:2.2.8
    License: The Apache Software License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0.txt)
`

**Comment by ravihariharan** [comment]
@BalusC  for WAS 9 i had to explicitly register the listener in web.xml before the StartupServletContextListener. 

```
<listener>
		<listener-class>org.omnifaces.ApplicationListener</listener-class>
	</listener>
	<listener>
		<listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
	</listener>
```

**Comment by ravihariharan** [comment]
Without the ApplicationListener
```
[2/22/19 14:59:29:238 EST] 0000015f ApplicationMg A   WSVR0200I: Starting application: WasWebSocketTestApp_war
[2/22/19 14:59:29:238 EST] 0000015f ApplicationMg A   WSVR0204I: Application: WasWebSocketTestApp_war  Application build level: Unknown
[2/22/19 14:59:29:738 EST] 0000015f webapp        I com.ibm.ws.webcontainer.webapp.WebGroupImpl WebGroup SRVE0169I: Loading Web Module: WasWebSocketTestApp.
[2/22/19 14:59:29:754 EST] 0000015f WASSessionCor I SessionContextRegistry getSessionContext SESN0176I: Will create a new session context for application key default_host/WasWebSocketTestApp
[2/22/19 14:59:29:848 EST] 0000015f ApplicationIn I   Using OmniFaces version 2.7
[2/22/19 14:59:29:848 EST] 0000015f DefaultFacesC I   Reading standard config META-INF/standard-faces-config.xml
[2/22/19 14:59:29:879 EST] 0000015f DefaultFacesC I   Reading config /WEB-INF/faces-config.xml
[2/22/19 14:59:30:035 EST] 0000015f DefaultFacesC I   Reading config : bundleresource://122.fwk343829293/META-INF/faces-config.xml
[2/22/19 14:59:30:035 EST] 0000015f DefaultFacesC I   Reading config : wsjar:file:/C:/Program%20Files/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/LeanDevWASNode01Cell/WasWebSocketTestApp_war.ear/WasWebSocketTestApp.war/WEB-INF/lib/omnifaces-2.7.jar!/META-INF/faces-config.xml
[2/22/19 14:59:30:145 EST] 0000015f DefaultInject I   Using InjectionProvider com.ibm.ws.jsf.spi.impl.WASCDIAnnotationDelegateInjectionProvider
[2/22/19 14:59:30:160 EST] 0000015f ApplicationIm I   Couldn't discover the current project stage, using Production
[2/22/19 14:59:30:160 EST] 0000015f FacesConfigur I   Serialization provider : class org.apache.myfaces.shared_impl.util.serial.DefaultSerialFactory
[2/22/19 14:59:30:160 EST] 0000015f AbstractFaces I   ServletContext initialized.
[2/22/19 14:59:30:160 EST] 0000015f WebConfigPara I   Tomahawk jar not available. Autoscrolling, DetectJavascript, AddResourceClass and CheckExtensionsFilter are disabled now.
[2/22/19 14:59:30:160 EST] 0000015f WebConfigPara I   Scanning for context init parameters not defined. It is not necessary to define them all into your web.xml, they are just provided here for informative purposes. To disable this messages set org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS config param to 'false'
[2/22/19 14:59:30:160 EST] 0000015f WebConfigPara I   No context init parameter 'javax.faces.RESOURCE_EXCLUDES' found, using default value '.class .jsp .jspx .properties .xhtml .groovy'.

```

**Comment by ravihariharan** [comment]
With the ApplicationListener in web.xml

we can see in logs 
`[2/22/19 15:01:41:442 EST] 0000015f EndpointManag I   CWWKH0046I: Adding a WebSocket ServerEndpoint with the following URI: /omnifaces.push/{channel}`

```
[2/22/19 15:01:40:817 EST] 0000015f ApplicationMg A   WSVR0200I: Starting application: WasWebSocketTestApp_war
[2/22/19 15:01:40:817 EST] 0000015f ApplicationMg A   WSVR0204I: Application: WasWebSocketTestApp_war  Application build level: Unknown
[2/22/19 15:01:41:332 EST] 0000015f webapp        I com.ibm.ws.webcontainer.webapp.WebGroupImpl WebGroup SRVE0169I: Loading Web Module: WasWebSocketTestApp.
[2/22/19 15:01:41:332 EST] 0000015f WASSessionCor I SessionContextRegistry getSessionContext SESN0176I: Will create a new session context for application key default_host/WasWebSocketTestApp
[2/22/19 15:01:41:426 EST] 0000015f ApplicationIn I   Using OmniFaces version 2.7
[2/22/19 15:01:41:442 EST] 0000015f EndpointManag I   CWWKH0046I: Adding a WebSocket ServerEndpoint with the following URI: /omnifaces.push/{channel}
[2/22/19 15:01:41:442 EST] 0000015f DefaultFacesC I   Reading standard config META-INF/standard-faces-config.xml
[2/22/19 15:01:41:473 EST] 0000015f DefaultFacesC I   Reading config /WEB-INF/faces-config.xml
[2/22/19 15:01:41:629 EST] 0000015f DefaultFacesC I   Reading config : bundleresource://122.fwk343829293/META-INF/faces-config.xml
[2/22/19 15:01:41:629 EST] 0000015f DefaultFacesC I   Reading config : wsjar:file:/C:/Program%20Files/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/LeanDevWASNode01Cell/WasWebSocketTestApp_war.ear/WasWebSocketTestApp.war/WEB-INF/lib/omnifaces-2.7.jar!/META-INF/faces-config.xml
[2/22/19 15:01:41:723 EST] 0000015f DefaultInject I   Using InjectionProvider com.ibm.ws.jsf.spi.impl.WASCDIAnnotationDelegateInjectionProvider
[2/22/19 15:01:41:739 EST] 0000015f ApplicationIm I   Couldn't discover the current project stage, using Production
[2/22/19 15:01:41:739 EST] 0000015f FacesConfigur I   Serialization provider : class org.apache.myfaces.shared_impl.util.serial.DefaultSerialFactory
[2/22/19 15:01:41:739 EST] 0000015f AbstractFaces I   ServletContext initialized.
[2/22/19 15:01:41:739 EST] 0000015f WebConfigPara I   Tomahawk jar not available. Autoscrolling, DetectJavascript, AddResourceClass and CheckExtensionsFilter are disabled now.
[2/22/19 15:01:41:739 EST] 0000015f WebConfigPara I   Scanning for context init parameters not defined. It is not necessary to define them all into your web.xml, they are just provided here for informative purposes. To disable this messages set org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS config param to 'false'
[2/22/19 15:01:41:739 EST] 0000015f WebConfigPara I   No context init parameter 'javax.faces.RESOURCE_EXCLUDES' found, using default value '.class .jsp .jspx .properties .xhtml .groovy'.
[2/22/19 15:01:41:739 EST] 0000015f WebConfigPara I   No context init parameter 'javax.faces.STATE_SAVING_METHOD' found, using default value 'server'.

```

**Comment by ravihariharan** [comment]
@BalusC  leave this open for your review and possible documentation update for know issues with WAS

**Comment by BalusC** [comment]
Thanks for documenting the work around.

This behavior is however unexpected. Do you have any `<absolute-ordering>` configured in webapp's `web.xml` to control loading of libraries?

OmniFaces itself has in its `web-fragment.xml` the below configuration:

```	<ordering>
		<after>
			<others />
		</after>
	</ordering>
```
Thus the server must obey this unless overridden or buggy.

**Comment by ravihariharan** [comment]
@BalusC  I have not defined any `<absolute-ordering>` in the web.xml
