### ISSUE TITLE
<o:websocket/> with <distributable/>  org.infinispan.commons.marshall.NotSerializableException: io.undertow.websockets.core.protocol.version13.WebSocket13Channel

### ISSUE THREAD

**Issue by tomlux** [omnifaces/omnifaces#510]
I have running a simple webapp running under Wildfly16 in FullHA-domain-mode.

When deploying my application marked with "<distributable/>" in web.xml, I'm getting NotSerializableException for the WebSocket13Channel.

How can I use the WebSockets in a clustered environment?
Is this a bug?

Thanks, 
Tom

`Caused by: org.infinispan.commons.marshall.NotSerializableException: io.undertow.websockets.core.protocol.version13.WebSocket13Channel
        Suppressed: org.infinispan.util.logging.TraceException
                at org.infinispan.interceptors.impl.SimpleAsyncInvocationStage.get(SimpleAsyncInvocationStage.java:41)
                at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:250)
                at org.infinispan.transaction.impl.TransactionCoordinator.commit(TransactionCoordinator.java:156)
                at org.infinispan.transaction.impl.TransactionTable.afterCompletion(TransactionTable.java:861)
                at org.infinispan.transaction.synchronization.SynchronizationAdapter.afterCompletion(SynchronizationAdapter.java:33)
                at org.infinispan.commons.tx.TransactionImpl.notifyAfterCompletion(TransactionImpl.java:506)
                at org.infinispan.commons.tx.TransactionImpl.runCommit(TransactionImpl.java:338)
                at org.infinispan.commons.tx.TransactionImpl.commit(TransactionImpl.java:110)
                at org.wildfly.clustering.ee.infinispan.InfinispanBatch.close(InfinispanBatch.java:97)
                at org.wildfly.clustering.web.undertow.session.DistributableSession.requestDone(DistributableSession.java:87)
                at io.undertow.servlet.spec.ServletContextImpl.updateSessionAccessTime(ServletContextImpl.java:945)
                at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:579)
                at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:351)
                at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
                at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
                at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
                at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
                at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
                at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
                at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction$$Lambda$1188/690175089.call(Unknown Source)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$1189/1666240586.call(Unknown Source)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$1189/1666240586.call(Unknown Source)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$1189/1666240586.call(Unknown Source)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$1189/1666240586.call(Unknown Source)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
                at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$1189/1666240586.call(Unknown Source)
                at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
                at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
                at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
                at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
                at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
                at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
                at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
                at java.lang.Thread.run(Thread.java:745)
Caused by: an exception which occurred:
        in object io.undertow.websockets.core.protocol.version13.WebSocket13Channel@96d608a
        in object java.util.ArrayList@5e2143bc
        in object java.util.HashMap@3409e65c
`

**Comment by BalusC** [comment]
> io.undertow.websockets.core.protocol.version13.WebSocket13Channel@96d608a in object java.util.ArrayList@5e2143bc in object java.util.HashMap@3409e65c

The `<o:socket>` isn't doing that. If anything, the `SocketChannelManager` is the only place where socket sessions are tracked, but it's doing that in a `ConcurrentLinkedQueue` in a `ConcurrentHashMap`.

I suspect a bug in either WildFly or in your own webapp. A reproducer would be helpful to understand the cause of your problem.

**Comment by tomlux** [comment]
yes, already created a ticket on wildfly
