### ISSUE TITLE
o:cache fails when the response was already commited

### ISSUE THREAD

**Issue by mwalliczek** [omnifaces/omnifaces#520]
When using o:cache with default config (sessionScoped) at a logout.xhtml page where a f:viewAction triggers a session invalidation and a redirect, o:cache will cause an IllegalStateException:

```
2019-06-25 13:36:34,642 ERROR j.e.r.w.j.application [https-jsse-nio2-16002-exec-4] Error Rendering View[/faces/guest/logout.xhtml]
java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3034) ~[catalina.jar:8.5.41]
	at org.apache.catalina.connector.Request.getSession(Request.java:2468) ~[catalina.jar:8.5.41]
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896) ~[catalina.jar:8.5.41]
	at com.sun.faces.context.ExternalContextImpl.getSession(ExternalContextImpl.java:157) ~[jakarta.faces-2.3.9.jar:2.3.9]
	at javax.faces.context.ExternalContextWrapper.getSession(ExternalContextWrapper.java:456) ~[jakarta.faces-2.3.9.jar:2.3.9]
	at javax.faces.context.ExternalContextWrapper.getSession(ExternalContextWrapper.java:456) ~[jakarta.faces-2.3.9.jar:2.3.9]
	at javax.faces.context.ExternalContextWrapper.getSession(ExternalContextWrapper.java:456) ~[jakarta.faces-2.3.9.jar:2.3.9]
	at org.omnifaces.util.cache.CacheInstancePerScopeProvider.getSessionScopeCache(CacheInstancePerScopeProvider.java:102) ~[omnifaces-3.3.jar:3.3]
	at org.omnifaces.util.cache.CacheInstancePerScopeProvider.getCache(CacheInstancePerScopeProvider.java:55) ~[omnifaces-3.3.jar:3.3]
	at org.omnifaces.util.cache.CacheFactory.getCache(CacheFactory.java:45) ~[omnifaces-3.3.jar:3.3]
	at org.omnifaces.component.output.Cache.getCacheImpl(Cache.java:332) ~[omnifaces-3.3.jar:3.3]
	at org.omnifaces.component.output.Cache.encodeChildren(Cache.java:233) ~[omnifaces-3.3.jar:3.3]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647) ~[jakarta.faces-2.3.9.jar:2.3.9]
```

**Comment by BalusC** [comment]
I'm wondering why the component tree is encoded in spite of that a redirect is performed .. Normally this should not happen in first place. How exactly is your f:viewAction performing a redirect?

**Comment by BalusC** [comment]
Anyway.

Closing off as norepro.

In case you want to redirect within JSF context, make sure you use `ExternalContext#redirect()`. Or if you're really forced to use `HttpServletResponse#sendRedirect()` for some reason, then you need to manually invoke `FacesContext#responseComplete()` in order to instruct JSF that the response has been manually completed and thus it doesn't need to render the view.
