### ISSUE TITLE
Ocasionaly getting StackOverflowError

### ISSUE THREAD

**Issue by dhaalves** [omnifaces/omnifaces#523]
```
java.lang.StackOverflowError: null
    at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:284)
    at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:248)
    at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:99)
    at org.jboss.as.jsf.injection.weld.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:52)
    at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:50)
    at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:88)
    at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:162)
    at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
    at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
    at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:250)
    at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:248)
    at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:99)
    at org.jboss.as.jsf.injection.weld.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:52)
    at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:50)
    at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:88)
    at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:162)
    at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
    at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
    at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:250)
    at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:248)
    at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:99)
    at org.jboss.as.jsf.injection.weld.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:52)
    at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:50)
    at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:88)
    at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:162)
    at com.sun.faces.util.MessageFactory.getApplication(MessageFactory.java:286)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:158)
    at com.sun.faces.util.MessageFactory.getMessage(MessageFactory.java:136)
    at com.sun.faces.util.MessageUtils.getExceptionMessageString(MessageUtils.java:388)
    at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:250)
    at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:248)

```
After that I keep getting tons of "Multiple JSF Applications found on same ClassLoader.  Unable to safely determine which FactoryManager instance to use. Defaulting to first match"

I cannot figure out the cause.
I am using omnifaces 3.3, Primefaces 7 with Jboss EAP 7.2.3

**Comment by BalusC** [comment]
Are you deploying a WAR or an EAR?

If WAR, please unzip it and list all files in /WEB-INF/lib folder.
If EAR, please unzip it and list all files in /lib folder as well as the /WEB-INF/lib folder of the WAR it is containing.

This way I can help you pointing out the duplicate libraries so you know which ones to remove.

**Comment by dhaalves** [comment]
Hello @BalusC

I am deploying WAR, here are the jars under /WEB-INF/lib folder

> api-util-2019.09.1.jar
> bcpkix-jdk15on-1.60.0.redhat-00001.jar
> bcprov-jdk15on-1.60.0.redhat-00001.jar
> commons-beanutils-1.9.3.redhat-1.jar
> commons-codec-1.11.0.redhat-00001.jar
> commons-collections-3.2.2.redhat-2.jar
> commons-collections4-4.3.jar
> commons-db-2019.09.1.jar
> commons-imaging-1.0-SNAPSHOT.jar
> commons-io-2.5.0.redhat-3.jar
> commons-lang3-3.8.1.jar
> commons-logging-1.2.jar
> commons-text-1.6.jar
> core-db-2019.09.1.jar
> core-web-2019.09.1.jar
> dirf-client-2019.09.1.jar
> fluent-hibernate-core-0.3.1.jar
> google-api-client-1.21.0.jar
> google-api-services-calendar-v3-rev157-1.21.0.jar
> google-api-services-drive-v3-rev2-1.21.0.jar
> google-http-client-1.21.0.jar
> google-http-client-jackson2-1.21.0.jar
> google-http-client-jdo-1.21.0.jar
> google-oauth-client-1.21.0.jar
> google-oauth-client-java6-1.21.0.jar
> google-oauth-client-jetty-1.21.0.jar
> google-oauth-client-servlet-1.21.0.jar
> grad-db-2019.09.1.jar
> guava-jdk5-17.0.jar
> httpclient-4.5.2.redhat-2.jar
> httpcore-4.4.4.redhat-2.jar
> itextpdf-5.5.13.jar
> itext-xtra-5.5.13.jar
> java-gitlab-api-4.1.0.jar
> jdo2-api-2.3-eb.jar
> jdom2-2.0.6.jar
> jetty-6.1.26.jar
> jetty-util-6.1.26.jar
> json-20090211.jar
> jsr305-1.3.9.jar
> keycloak-admin-client-4.8.3.Final.jar
> keycloak-common-4.8.3.Final.jar
> keycloak-core-4.8.3.Final.jar
> mybatis-3.4.6.jar
> mybatis-cdi-1.0.3.jar
> mybatis-generator-core-1.3.7.jar
> notificacao-uel-client-2019.09.1.jar
> omnifaces-3.3.jar
> primefaces-7.0.jar
> redmine-java-api-3.0.0.jar
> rome-1.9.0.jar
> rome-utils-1.9.0.jar
> slf4j-api-1.7.22.redhat-2.jar
> transaction-api-1.1.jar
> uel-2019.09.1.jar
> uel-db-2019.09.1.jar
> util-2019.09.1.jar
> velocity-engine-core-2.0.jar
> xmlpull-1.1.3.1.jar
> xpp3_min-1.1.4c.jar
> 

Also to complement, 

The following SEVERE messages occur **prior**  StackOverFlow ERROR
```
2019-09-16 09:13:51,207 SEVERE [javax.faces] (default task-287) Unable to obtain InjectionProvider from init time FacesContext. Does this container implement the Mojarra Injection SPI?
2019-09-16 09:13:51,209 SEVERE [javax.faces] (default task-287) Unable to inject com.sun.faces.application.ApplicationFactoryImpl@74ed8c5f because no InjectionProvider can be found. Does this container implement the Mojarra Injection SPI?
2019-09-16 09:13:51,213 SEVERE [javax.faces] (default task-287) Unable to inject com.sun.faces.application.ApplicationFactoryImpl@74ed8c5f because no InjectionProvider can be found. Does this container implement the Mojarra Injection SPI?
2019-09-16 09:13:51,215 SEVERE [javax.faces] (default task-287) Unable to inject org.omnifaces.application.OmniApplicationFactory@225a5553 because no InjectionProvider can be found. Does this container implement the Mojarra Injection SPI?
2019-09-16 09:13:51,218 SEVERE [javax.faces] (default task-287) Unable to inject com.sun.faces.application.InjectionApplicationFactory@4c183149 because no InjectionProvider can be found. Does this container implement the Mojarra Injection SPI?
```


And the following occur **after** StackOverFlow ERROR
```
java.lang.IllegalStateException: ApplicationAssociate ctor not called in same callstack as ConfigureListener.contextInitialized()
    at com.sun.faces.application.ApplicationAssociate.<init>(ApplicationAssociate.java:244)
    at com.sun.faces.application.ApplicationImpl.<init>(ApplicationImpl.java:248)
    at com.sun.faces.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:99)
    at org.jboss.as.jsf.injection.weld.WeldApplicationFactory.getApplication(WeldApplicationFactory.java:52)
    at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:50)
    at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:88)
    at org.omnifaces.util.Faces.getApplicationFromFactory(Faces.java:276)
    at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:108)
    at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:84)
    at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
    at org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
    at org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
    at org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
    at org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
    at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
    at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
    at org.keycloak.adapters.elytron.KeycloakServletExtension.lambda$null$0(KeycloakServletExtension.java:39)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.MetricsHandler.handleRequest(MetricsHandler.java:64)
    at io.undertow.servlet.core.MetricsChainHandler.handleRequest(MetricsChainHandler.java:59)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by dhaalves** [comment]
I have some clues why that might be happening,

So... on my core-web module (core-web.jar), I have a dynamic filter for protected pages where I load userInfo from keycloak and notify (via CDI events) a SessionScopedBean in my application when a user logs in.
I manually initialize FacesContext there (`initFacesContext(request, response);`) so it will be available to my SessionScopedBean

```java
public class KeycloakLoginFilter extends HttpFilter {

    @Inject
    private UsuarioController usuarioController;

    @Override
    public void doFilter(HttpServletRequest request, HttpServletResponse response,
                         HttpSession session, FilterChain chain) throws ServletException, IOException {
        KeycloakSecurityContext securityContext =
                (KeycloakSecurityContext) session.getAttribute(KeycloakSecurityContext.class.getName());
        if (securityContext != null && usuarioController.getUsuario() == null) {
            initFacesContext(request, response);
            try {
                usuarioController.carregaUsuario(securityContext.getRealm(),
                        securityContext.getTokenString());
            } catch (Exception e) {
                Logger.getLogger(KeycloakLoginFilter.class).log(Logger.Level.ERROR, "Falha ao carregar informações " +
                        "usuário");
            }
        }
        chain.doFilter(request, response);
    }

    private void initFacesContext(HttpServletRequest request, HttpServletResponse response) {
        LifecycleFactory lifecycleFactory = (LifecycleFactory) FactoryFinder
                .getFactory(FactoryFinder.LIFECYCLE_FACTORY);
        Lifecycle lifecycle = lifecycleFactory
                .getLifecycle(LifecycleFactory.DEFAULT_LIFECYCLE);
        FacesContextFactory contextFactory =
                (FacesContextFactory) FactoryFinder.getFactory(FactoryFinder.FACES_CONTEXT_FACTORY);
        contextFactory.getFacesContext(
                request.getSession().getServletContext(), request, response, lifecycle);
    }


    private void registerWebFilter(@Observes @Initialized(ApplicationScoped.class) ServletContext servletContext) {
        FilterRegistration fr = servletContext.addFilter("KeycloakLoginFilter", KeycloakLoginFilter.class);
        Map<String, Set<String>> securityConstraints = ServerUtil.getSecurityConstraints(servletContext);
        fr.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST),
                true, securityConstraints.keySet().toArray(new String[0]));
    }
    
}

```

```java
@Named
@SessionScoped
public class UsuarioController implements Serializable {

    @Inject
    private Event<Usuario> event;
    private Usuario usuario;
    private static final String USER_INFO_URL = "https://<domain>/auth/realms/{realm}/protocol/openid-connect/userinfo";


    public Usuario carregaUsuario(String realm, String token) {
        Client client = ClientBuilder.newClient();
        Response response =
                client.target(USER_INFO_URL)
                        .resolveTemplate("realm", realm)
                        .request()
                        .header(HttpHeaders.AUTHORIZATION, "bearer " + token)
                        .get();
        usuario = response.readEntity(Usuario.class);
        event.fire(usuario);
        return usuario;
    }


    public Usuario getUsuario() {
        return usuario;
    }
```
The point is that code was in production for  about 8 month and this never happened, just recently when we change from Jboss EAP 7.1.x (based on wildfly 11 - Java EE 7) for Jboss EAP 7.2 (based on wildfly 14 and JavaEE8 compilant) this start to happen.

**Comment by BalusC** [comment]
This is essentially caused by having multiple JSF applications in the same context. I can do little from OmniFaces side on. I recommend to replace the manual initialization of FacesContext by something else which doesn't require manual initialization of FacesContext. E.g. by using pure CDI.
