### ISSUE TITLE
error deployment app tomee 8.0.1

### ISSUE THREAD

**Issue by psborges84** [omnifaces/omnifaces#543]
Hello,
I'm using apache-tomee-8.0.1 + primefaces 7.0.12 + omnifaces-3.4.1.
when starting tomcat the following error appears below

mar 05, 2020 10:16:13 AM org.apache.myfaces.spi.impl.DefaultInjectionProviderFactory getInjectionProvider
INFORMAÇÕES: Using InjectionProvider org.apache.myfaces.spi.impl.Tomcat7AnnotationInjectionProvider
mar 05, 2020 10:16:13 AM org.apache.myfaces.webapp.AbstractFacesInitializer initFaces
GRAVE: An error occured while initializing MyFaces: org.apache.openejb.core.ivm.naming.LazyObjectReference$LazyNamingException: On a thread without an initialized context nor a classloader mapping a deployed app
java.lang.IllegalStateException: org.apache.openejb.core.ivm.naming.LazyObjectReference$LazyNamingException: On a thread without an initialized context nor a classloader mapping a deployed app
	at org.omnifaces.util.JNDI.lookup(JNDI.java:107)
	at org.omnifaces.util.Beans.getManager(Beans.java:97)
	at org.omnifaces.util.Beans.getReference(Beans.java:141)
	at org.omnifaces.application.OmniApplication.<init>(OmniApplication.java:67)
	at org.omnifaces.application.OmniApplicationFactory.createOmniApplication(OmniApplicationFactory.java:77)
	at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:50)
	at org.apache.myfaces.config.FacesConfigurator.configureApplication(FacesConfigurator.java:710)
	at org.apache.myfaces.config.FacesConfigurator.configure(FacesConfigurator.java:606)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.buildConfiguration(AbstractFacesInitializer.java:456)
	at org.apache.myfaces.webapp.Jsp21FacesInitializer.initContainerIntegration(Jsp21FacesInitializer.java:70)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:190)
	at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4683)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
Caused by: org.apache.openejb.core.ivm.naming.LazyObjectReference$LazyNamingException: On a thread without an initialized context nor a classloader mapping a deployed app
	at org.apache.openejb.core.ivm.naming.LazyObjectReference.getObject(LazyObjectReference.java:39)
	at org.apache.openejb.core.ivm.naming.Reference.getContent(Reference.java:38)
	at org.apache.xbean.naming.reference.SimpleReference$SimpleObjectFactory.getObjectInstance(SimpleReference.java:137)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:857)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:160)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:843)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:174)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.omnifaces.util.JNDI.lookup(JNDI.java:102)
	... 52 more

**Comment by BalusC** [comment]
Sorry, norepro with `apache-tomee-8.0.1-webprofile.zip` with an empty maven WAR project with only OmniFaces 3.4.1 as dependency.

```
INFO: Server version name:   Apache Tomcat (TomEE)/9.0.30 (8.0.1)
INFO: Using OmniFaces version 3.4
INFO: MyFaces Core has started, it took [503] ms.
INFO: Server startup in [2,502] milliseconds
```

Try creating a reproducer project.

**Comment by BalusC** [comment]
IT tests have been migrated from TomEE 8.0.0-M2 to TomEE 8.0.1. They all pass successfully.

Closing off as not an OmniFaces problem.
