### ISSUE TITLE
MultiViews (FacesViews) exclude pattern: Path does not start with a "/" character

### ISSUE THREAD

**Issue by rripley** [omnifaces/omnifaces#551]
When using the exclude pattern feature of MultiViews as documented [here](https://omnifaces.org/docs/javadoc/3.5/org/omnifaces/facesviews/package-summary.html), OmniFaces fails to initialize with the exception that the path does not start with a "/". 

OmniFaces 3.5 on TomEE 8.0.1

```
<context-param>
	<param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
	<param-value>/*.xhtml/*,!/api,!/push</param-value>
</context-param>
```

```
Caused by: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
	at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:57)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 27 more
Caused by: java.lang.IllegalArgumentException: Path [!/api/] does not start with a "/" character
	at org.apache.catalina.core.ApplicationContext.getResourcePaths(ApplicationContext.java:596)
	at org.apache.catalina.core.ApplicationContextFacade.getResourcePaths(ApplicationContextFacade.java:180)
	at org.omnifaces.facesviews.FacesViews.scanAndStoreViews(FacesViews.java:370)
	at org.omnifaces.facesviews.FacesViews.registerForwardingFilter(FacesViews.java:266)
	at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:54)
	... 29 more
```

**Comment by BalusC** [comment]
Fixed, thanks for reporting! It's now also covered by IT tests.
