### ISSUE TITLE
Initialization error on jakarta.faces 2.3.13.

### ISSUE THREAD

**Issue by lmierzwinski-InfintieProgress** [omnifaces/omnifaces#558]
Hi,

I have problem with dialogs on priemefases so I changed jsf implementation on wildfly 18 (jsf-impl-2.3.9.SP04) to jakarta faces 2.3.13. Jakarta faces is defautl on PrimeFaces showcase. 

After jsf impl change there is problem with OmniFaces initialization. I try from 2.3.10 to 2.3.14.

Stack trace:
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 8 more
Caused by: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:88)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	... 10 more
Caused by: java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    javax/faces/component/UIComponentBase.getValueBinding(Ljava/lang/String;)Ljavax/faces/el/ValueBinding; @58: aload_2
  Reason:
    Type 'com/sun/faces/application/ValueBindingValueExpressionAdapter' (current frame, locals[2]) is not assignable to 'javax/faces/el/ValueBinding' (stack map, locals[2])
  Current Frame:
    bci: @58
    flags: { }
    locals: { 'javax/faces/component/UIComponentBase', 'java/lang/String', 'com/sun/faces/application/ValueBindingValueExpressionAdapter', 'javax/el/ValueExpression' }
    stack: { }
  Stackmap Frame:
    bci: @58
    flags: { }
    locals: { 'javax/faces/component/UIComponentBase', 'java/lang/String', 'javax/faces/el/ValueBinding', 'javax/el/ValueExpression' }
    stack: { }
  Bytecode:
    0x0000000: 2bc7 000b bb00 1059 b700 11bf 014d 012a
    0x0000010: 2bb6 0138 594e a500 242d b600 7b13 0139
    0x0000020: b600 9199 000e 2dc0 0139 b601 3a4d a700
    0x0000030: 0cbb 013b 592d b701 3c4d 2cb0          
  Stackmap Table:
    same_frame(@12)
    append_frame(@49,Object[#729],Object[#730])
    same_frame(@58)

	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:85)
	... 21 more

**Comment by melloware** [comment]
When you say you changed the jsf-impl what exactly do you mean updated the module and module.xml with 2.3.14?

**Comment by lmierzwinski-InfintieProgress** [comment]
Yes, I have updated the module and module.xml with 2.3.14.

**Comment by BalusC** [comment]
Norepro when I follow the upgrade instructions in https://stackoverflow.com/questions/35899887/how-to-install-one-jar-variant-of-jsf-2-3-javax-faces-jar-on-wildfly
