### ISSUE TITLE
ClassCastException occurs when using ToCollectionConverter depending on the element type.

### ISSUE THREAD

**Issue by maruTA-bis5** [omnifaces/omnifaces#576]
If the element stored in Collection is other than java.lang.String, ClassCastException may occur when using `omnifaces.ToCollectionConverter`.

### Example
The source code not omitted is here: https://github.com/maruTA-bis5/primefaces-test/tree/omnifaces-tocollectionconverter-with-enumconverter

#### Example xhtml
```html
<f:metadata>
    <f:viewParam name="parameter" value="#{testView.parameter}">
        <o:converter converterId="omnifaces.ToCollectionConverter" 
            itemConverter="omnifaces.GenericEnumConverter" />
    </f:viewParam>
</f:metadata>
```

#### Example backing bean
```java
@Model
public class TestView {

    public enum TestEnum {
        FIRST, SECOND, THIRD;
    }

    private Set<TestEnum> parameter = new HashSet<>();

    public Set<TestEnum> getParameter() {
        return parameter;
    }

    public void setParameter(Set<TestEnum> parameter) {
        this.parameter = parameter;
    }
```

### Observed exception
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Enum (java.lang.String and java.lang.Enum are in module java.base of loader 'bootstrap')
	at org.omnifaces.converter.GenericEnumConverter.getAsString(GenericEnumConverter.java:94)
	at org.omnifaces.converter.ToCollectionConverter.getAsObject(ToCollectionConverter.java:120)
	at org.omnifaces.converter.ToCollectionConverter.getAsObject(ToCollectionConverter.java:72)
	at org.omnifaces.taghandler.Converter$1.getAsObject(Converter.java:118)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getConvertedValue(HtmlBasicInputRenderer.java:147)
	at javax.faces.component.UIViewParameter.getConvertedValue(UIViewParameter.java:458)
	at javax.faces.component.UIInput.validate(UIInput.java:1006)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1317)
	at javax.faces.component.UIInput.processValidators(UIInput.java:733)
	at javax.faces.component.UIViewParameter.processValidators(UIViewParameter.java:279)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1310)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
```

**Comment by BalusC** [comment]
I see. The problem is two-fold.

1. The `ToCollectionConverter.java:120` has a bug. It should have invoked `getAsObject()` instead of `getAsString()`. I have fixed it for 2.7.8 and 3.8.1.
2. The `omnifaces.GenericEnumConverter` is insuitable for the purpose. Remove it and it'll work again whereby the built-in `javax.faces.convert.EnumConverter` will be auto-utilized.

```
<f:metadata>
    <f:viewParam name="parameter" value="#{testView.parameter}">
        <o:converter converterId="omnifaces.ToCollectionConverter" />
    </f:viewParam>
</f:metadata>
```

Thank you for improving OmniFaces!
