### ISSUE TITLE
ViewExpiredExceptionHandler.wasViewExpired causes NPE in Mojarra (Flash)

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#591]
There is an outstanding issue with Mojarra Flash that causes NPE.
https://github.com/eclipse-ee4j/mojarra/issues/4431
See https://github.com/flowlogix/flowlogix/tree/OmniFaces-Integration-3.9/jakarta-ee/jee-examples for automated test
In my original code, I had that function surrounded by `if ()` statement in order not to hit that NPE:
```
    public static boolean wasViewExpired() {
        boolean viewExpired = false;
        if (!Faces.isAjaxRequest() && !Faces.isSessionNew()) {
            viewExpired = Faces.getFlashAttribute(FLASH_ATTRIBUTE_VIEW_EXPIRED, () -> false);
        }
        return viewExpired;
    }
```
However, the new code runs into this error, with the below exception:

```
[#|2020-11-26T23:27:11.392-0600|SEVERE|Payara 5.2020.7-SNAPSHOT|javax.enterprise.resource.webcontainer.jsf.application|_ThreadID=82;_ThreadName=http-thread-pool::http-listener-1(5);_TimeMillis=1606454831392;_LevelValue=1000;|
  Error Rendering View[/exception-pages.xhtml]
javax.el.ELException: /exception-pages.xhtml: java.lang.NullPointerException
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:47)
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:41)
	at com.sun.faces.facelets.compiler.UILeaf.encodeAll(UILeaf.java:169)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.sun.faces.context.flash.ELFlash.get(ELFlash.java:396)
	at org.omnifaces.util.FacesLocal.getFlashAttribute(FacesLocal.java:1574)
	at org.omnifaces.util.Faces.getFlashAttribute(Faces.java:2255)
	at org.omnifaces.exceptionhandler.ViewExpiredExceptionHandler.wasViewExpired(ViewExpiredExceptionHandler.java:138)
	at com.flowlogix.examples.ui.ExceptionBean.expired(ExceptionBean.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:239)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:440)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:198)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:110)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:177)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:183)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.ELText$ELTextVariable.writeText(ELText.java:216)
	at com.sun.faces.facelets.el.ELText$ELTextComposite.writeText(ELText.java:123)
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:44)
	... 49 more
|#]
```

**Comment by BalusC** [comment]
I'm confused which use case exactly causes this as the ViewExpiredExceptionHandlerIT does pretty much the same thing and it passes fine. I'm also confused whether it shouldn't actually return `true` to "was view expired?".

**Comment by lprimak** [comment]
Below is the screenshot of the use case.
- User clicks on an AJAX button (view expired)
- is redirected back to the same page
- user redirected to a login screen

This is when `wasViewExpired()` returns `true` and prompts the message "your session has expired" to appear.
Obviously, when the user logs in for the first time, `wasViewExpired()` would return `false`

![Screen Shot 2020-11-28 at 1 14 18 PM](https://user-images.githubusercontent.com/1002484/100524184-a42bbb80-317b-11eb-9ac7-bda08e4b2d1c.png)

**Comment by BalusC** [comment]
"View expired" is not the same as "Session expired".

I'll try copying your test case. To be sure, you're specifically referring to `invalidSession()` test here: https://github.com/flowlogix/flowlogix/blob/OmniFaces-Integration-3.9/jakarta-ee/jee-examples/src/test/java/com/flowlogix/examples/ExceptionPageTest.java#L102 ?

**Comment by lprimak** [comment]
yes.
I am looking at this from the user's perspective. Users couldn't care less what 'expired' they just want to log back in and do their job.

**Comment by lprimak** [comment]
Waiting for this issue to be resolved so I can test #592 with the filter

**Comment by BalusC** [comment]
I've not been able to reproduce it so I'll need more time.

If you could describe the exact use case that would be very helpful.

**Comment by BalusC** [comment]
I've been able to reproduce it in Payara 5.2020.4 using exactly the existing `ViewExpiredExceptionHandlerIT` test case but then with `<distributable/>` flag set in `web.xml`. It indeed threw the described NPE already during page load. It worked fine in other test servers (WildFly 20.0.1 and TomEE 8.0.4).

**Comment by BalusC** [comment]
I've added a patch. It was not related to `ViewExpiredExceptionHandler`. It's just a general problem. I've also updated the IT to cover this case.

Thanks for reporting!

**Comment by lprimak** [comment]
Thanks, that is a good generic fix.
