### ISSUE TITLE
Another Flash NPE related to post-back with non-existent session

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#594]
Here there  is another missed case of the same NPE that was missed in the original fix
Reproduced when redeploying the app and reloading the page after Ajax call (post-back)

Relates to #591 

```
[#|2020-12-05T13:27:23.745-0600|SEVERE|Payara 5.2020.8-SNAPSHOT|javax.enterprise.resource.webcontainer.jsf.application|_ThreadID=85;_ThreadName=http-thread-pool::http-listener-1(3);_TimeMillis=1607196443745;_LevelValue=1000;|
  Error Rendering View[/exception-pages.xhtml]
javax.el.ELException: /exception-pages.xhtml: java.lang.NullPointerException
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:47)
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:41)
	at com.sun.faces.facelets.compiler.UILeaf.encodeAll(UILeaf.java:169)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.sun.faces.context.flash.ELFlash.get(ELFlash.java:396)
	at org.omnifaces.util.FacesLocal.getFlashAttribute(FacesLocal.java:1574)
	at org.omnifaces.util.Faces.getFlashAttribute(Faces.java:2255)
	at org.omnifaces.exceptionhandler.ViewExpiredExceptionHandler.wasViewExpired(ViewExpiredExceptionHandler.java:138)
	at com.flowlogix.examples.ui.ExceptionBean.expired(ExceptionBean.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:239)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:440)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:198)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:110)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:177)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:183)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.ELText$ELTextVariable.writeText(ELText.java:216)
	at com.sun.faces.facelets.el.ELText$ELTextComposite.writeText(ELText.java:123)
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:44)
	... 49 more
|#]
```

**Comment by lprimak** [comment]
Reproducer is the same as in #593

**Comment by BalusC** [comment]
Right, technically speaking the session is not anymore new. I'll have to remove that check.

**Comment by BalusC** [comment]
Reopening, it was mentioned in #597 that this is still happening.

**Comment by lprimak** [comment]
Can you please click around in my reproducer.
The only exceptions in the logs you should be getting is SQL exception.

**Comment by lprimak** [comment]
in no circumstance should there be `ClosedByInterruptException` or any other exception (other than SQL) in the logs no matter which button you click or how many times you redeploy the app

**Comment by BalusC** [comment]
I guess this is referring to issue #597 rather than to the flash issue.

**Comment by lprimak** [comment]
yes

**Comment by BalusC** [comment]
I've not been able to reproduce the NPE in ELFlash#get() after a redeploy.

The only thing with which I could reproduce something is the following use case:

- `web.xml` has `<distributable/>` flag set and context param `org.omnifaces.EXCEPTION_TYPES_TO_SUPPRESS` is set to `java.nio.channels.ClosedByInterruptException`
- `faces-config.xml` has `org.omnifaces.exceptionhandler.ViewExpiredExceptionHandlerFactory` and `org.omnifaces.exceptionhandler.ExceptionSuppressorFactory` registered in this order
- deploy the app with your `exception-pages.xhtml` and `ExceptionBean` code
- start the server (I used WildFly 21 with Mojarra 2.3.14.SP01 in its all-default trim)
- open `exception-pages.xhtml` 
- click button "Throw ClosedByInterruptException - no responseComplete()"
- undeploy and redeploy the app
- without refreshing the page, click button "Throw ClosedByInterruptException - no responseComplete()" once again

This continues to work fine, but this will produce the following line in server logs:
```
SEVERE [javax.enterprise.resource.webcontainer.jsf.flash] (default task-2) JSF1094: Could not decode flash data from incoming cookie value Invalid characters in decrypted value.  Processing will continue, but the flash is unavailable for this request.
```
Which Mojarra version exactly were you using? I guess yours threw a NPE in this exact use case?

**Comment by lprimak** [comment]
I can reproduce this immediately by clicking 'Invalidate Session via Faces' button
Using Payara latest (2020.8-SNAPSHOT) to be exact but it will work with 2020.7 the same

**Comment by BalusC** [comment]
Hmm, had no negative effect at all. so I cannot debug either. I'll have to try Payara later so I can put a breakpoint.

**Comment by lprimak** [comment]
I think Payara sets distributable for all apps, and this is why you only get the issue with Payara. `WebXml.isDistributable()` returns false yet Mojarra thinks it's distributable.

**Comment by lprimak** [comment]
The problem is fixed when I add `<distributable/> to web.xml.
I think the isDistributable() check should be removed here

**Comment by BalusC** [comment]
Can you retry now?

**Comment by lprimak** [comment]
one sec

**Comment by lprimak** [comment]
Ok, that worked!
