### ISSUE TITLE
o:validateBean: Error finding message javax.faces.validator.BeanValidator.MESSAGE

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#629]
**OmniFaces** 2.7.10
**Jboss EAP** 7.1

Introduced by: https://github.com/omnifaces/omnifaces/issues/564

Using `o:validateBean` with 2.7.6 was working with 2.7.10 its failing with "Can't find resource for bundle java.util.PropertyResourceBundle, key javax.faces.validator.BeanValidator.MESSAGE".

Looking at the source code its trying to find that key in a Faces Message Bundle but shouldn't it be looking in `ValidationMessages.properties` according JSR-303 https://stackoverflow.com/questions/7700922/customize-bean-validation-message/7701069#7701069 ?    

CC @blutoorange

```
2021-04-27 15:53:25,289 SEVERE [org.omnifaces.exceptionhandler.FullAjaxExceptionHandler] (default task-7) FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/pages/error/500.jsf' will be shown.: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key javax.faces.validator.BeanValidator.MESSAGE
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean.formatMessage(ValidateBean.java:602)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean.access$1000(ValidateBean.java:236)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean$8.invoke(ValidateBean.java:527)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean$8.invoke(ValidateBean.java:523)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean$7.invoke(ValidateBean.java:469)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.taghandler.ValidateBean$7.invoke(ValidateBean.java:462)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.util.Components$ForEach$1.visit(Components.java:530)
	at deployment.accountmanager-1.6.13-SNAPSHOT.war//org.omnifaces.util.Components$ForEach$TypesVisitCallback.visit(Components.java:607)
	at com.sun.jsf-impl//com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:151)
```

**Comment by melloware** [comment]
As a note we added it to our Faces `<message-bundle>` and it works fine.  We were just was thrown off when I was doing research on this error why it wasn't in ValidationMessages.properties.  If this is all correct then feel free to close the ticket!

**Comment by BalusC** [comment]
`javax.faces.*` keyed messages should indeed go in `<message-bundle>`.

However this exception is in turn indeed a bug. The code incorrectly expected it to merely return `null` when it's absent.

I'll have to fix it by putting it in a try-catch.

**Comment by melloware** [comment]
OK thanks!
