### ISSUE TITLE
Regression? NPE in Components.getCurrentActionSource()

### ISSUE THREAD

**Issue by astappiev** [omnifaces/omnifaces#644]
Since updating to latest version (3.11.1) of OmiFaces we started receiving NPE notifications. It happens every time right after `ViewExpiredException`, because `Components.getCurrentActionSource()` can't retrieve `FacesContext`.

I think this happens after [this commit](https://github.com/omnifaces/omnifaces/commit/3552b12b4cfac19d162d17d647bd0bd187aa34ea) and my first question, why do we need to get `FacesContext.getCurrentInstance()` inside `Components.getCurrentActionSource()` if we already have it in `Hacks.isPrimeFacesAjaxRequest(FacesContext context)`?

```
2021-10-13 17:32:05 DEBUG de.l3s.learnweb.component.exceptionhandler.LearnwebExceptionHandler:54 - View expired [private data]
2021-10-13 17:32:05 FATAL de.l3s.learnweb.component.exceptionhandler.LearnwebExceptionHandler:56 - Fatal unhandled error on [private data]
java.lang.NullPointerException: null
	at org.omnifaces.util.Components.findComponentIgnoringIAE(Components.java:1684) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.util.Components.getCurrentForm(Components.java:935) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.util.Components.getCurrentActionSource(Components.java:983) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.util.Hacks.isPrimeFacesAjaxRequest(Hacks.java:354) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.util.Hacks.removeResourceDependencyState(Hacks.java:196) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.renderErrorPageView(FullAjaxExceptionHandler.java:558) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handleAjaxException(FullAjaxExceptionHandler.java:434) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handle(FullAjaxExceptionHandler.java:383) ~[omnifaces-3.11.1.jar:3.11.1]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:193) ~[myfaces-impl-2.3-next-M6.jar:2.3-next-M6]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:125) ~[myfaces-impl-2.3-next-M6.jar:2.3-next-M6]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:207) ~[myfaces-api-2.3-next-M6.jar:2.3-next-M6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.43]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.43]
	at de.l3s.learnweb.component.exceptionhandler.LearnwebExceptionFilter.doFilter(LearnwebExceptionFilter.java:39) [classes/:?]
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:57) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.43]
	at de.l3s.learnweb.web.RequestFilter.doFilter(RequestFilter.java:93) [classes/:?]
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:57) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.43]
	at de.l3s.learnweb.user.AuthFilter.doFilter(AuthFilter.java:69) [classes/:?]
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:57) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.43]
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) [urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.43]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.14.1.jar:2.14.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:9.0.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:9.0.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.43]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) [catalina.jar:9.0.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-coyote.jar:9.0.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887) [tomcat-coyote.jar:9.0.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684) [tomcat-coyote.jar:9.0.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.43]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by BalusC** [comment]
It was actually `context.getViewRoot()` which returned `null`, not `FacesContext.getCurrentInstance()`.

Fixed, thank you for reporting!

**Comment by astappiev** [comment]
True, mixed up during writing the issue. Thanks for fixing!

**Comment by BalusC** [comment]
2.7.13 / 3.11.2 / 4.0-M10 have been released with this fix.
