### ISSUE TITLE
Nested form checker triggers NPEs

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#653]
OmniFaces 3.11.2.

```
Caused by: java.lang.NullPointerException
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//ru.argustelecom.techservice.components.PortList.getPortType(PortList.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.el.api@1.0.13.Final//javax.el.ELUtil.invokeMethod(ELUtil.java:311)
	at javax.el.api@1.0.13.Final//javax.el.BeanELResolver.invoke(BeanELResolver.java:415)
	at javax.el.api@1.0.13.Final//javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.parser.AstValue.getValue(AstValue.java:135)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.parser.AstValue.getValue(AstValue.java:203)
	at org.glassfish.javax.el@3.0.1-b08-jbossorg-1//com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.jsf-impl@2.3.3.SP1-TASK-107518//com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:159)
	at com.sun.jsf-impl@2.3.3.SP1-TASK-107518//com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:200)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.extensions.component.switchcase.Switch.getValue(Switch.java:79)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.extensions.component.switchcase.Switch.evaluate(Switch.java:97)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.extensions.component.switchcase.Switch.visitTree(Switch.java:150)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.component.api.UIData.visitColumnContent(UIData.java:1014)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.component.api.UIData.visitRows(UIData.java:988)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.component.api.UIData.visitTree(UIData.java:842)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:927)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:177)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIForm.visitTree(UIForm.java:395)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.primefaces.component.api.UITabPanel.visitTree(UITabPanel.java:920)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.api@2.3.3.SP1//javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.omnifaces.util.Components$ForEach.invoke(Components.java:590)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.omnifaces.util.Components$ForEach.invoke(Components.java:573)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.omnifaces.viewhandler.OmniViewHandler.checkNestedForms(OmniViewHandler.java:238)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.omnifaces.viewhandler.OmniViewHandler.validateComponentTreeStructure(OmniViewHandler.java:234)
	at deployment.argus-enterprise-3.22.ear.webui-3.22.war//org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:129)
	at javax.faces.api@2.3.3.SP1//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
	at com.sun.jsf-impl@2.3.3.SP1-TASK-107518//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
	at com.sun.jsf-impl@2.3.3.SP1-TASK-107518//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.jsf-impl@2.3.3.SP1-TASK-107518//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.api@2.3.3.SP1//javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	... 79 more
```
This happens because pe:switch value gets evaluated in order to visit the pe:case. Normally this wouldn't happen because its ancestor is not rendered.
Would could be a solution?
1. Maybe Switch shouldn't evaluate the value when SKIP_ITERATION? Right now it does:
```
@Override
public boolean visitTree(final VisitContext context, final VisitCallback callback) {
	// mustn't evaluate cases during Restore View
	if (context.getFacesContext().getCurrentPhaseId() != PhaseId.RESTORE_VIEW) {
		evaluate();
	}
	return super.visitTree(context, callback);
}
```
Which I did in https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/362 . Why did I do it this way instead of checking for SKIP_ITERATION? Can't remember. SKIP_ITERATION would be set during RESTORE_VIEW, right?
2. Nested form checker could SKIP_UNRENDERED.
3. Provide an option to disable nested form checker? We have our own anyway.
4. Implement checker differently, without a separate tree visit?
Ours looks like this:
```
public class NestedFormChecker implements SystemEventListener {
	@Override
	public void processEvent(SystemEvent event) throws AbortProcessingException {
		UIComponent form = ((PostAddToViewEvent) event).getComponent();
		UIComponent parentForm = getParentForm(form);
		if (parentForm != null) {
			throw new IllegalStateException("Form " + form.getClientId() + " is nested inside another form "
					+ parentForm.getClientId());
		}
	}

	private UIComponent getParentForm(UIComponent form) {
		UIComponent parent = form.getParent();
		while (parent != null) {
			if (isForm(parent)) {
				return parent;
			}
			parent = parent.getParent();
		}
		return null;
	}

	@Override
	public boolean isListenerForSource(Object source) {
		return source instanceof UIComponent && isForm((UIComponent) source);
	}

	/**
	 * Based on Mojarra's {@link FormOmittedChecker.isForm(UIComponent)}
	 */
	private boolean isForm(UIComponent component) {
		return (component instanceof UIForm
				|| (component.getFamily() != null && component.getFamily().endsWith("Form")));
	}
}
```

P.S.: we don't respect nested forms in appended PF dialogs by design, IIRC since we've had cases where Mojarra couldn't find action source for actions coming from such dialog. It just silently didn't call the action method. It was a pretty hard to debug issue in a real app with complex facelet template composition, so we preferred to fail it preventively.

**Comment by BalusC** [comment]
Shouldn't the `evaluate()` itself check `isRendered()`?

Doing a tree visit is in hindsight indeed unnecessary. Simple children traversal has been sufficient.

**Comment by VsevolodGolovanov** [comment]
> Shouldn't the `evaluate()` itself check `isRendered()`?

Should it? javax.faces.component.UIData#visitTree doesn't. It calls isVisitable, that does
```
        if ((hints.contains(VisitHint.SKIP_UNRENDERED) && 
                !this.isRendered())                    ||
```
, but OmniViewHandler.checkNestedForms doesn't SKIP_UNRENDERED.

**Comment by BalusC** [comment]
I see. Having nested forms in the markup is however not a view render time related issue but a view build time related issue. So it shouldn't skip unrendered components.

I'll have to replace the tree visit by a children traversal.

**Comment by BalusC** [comment]
Done, will be in 2.7.15 / 3.13
