### ISSUE TITLE
o:inputFile with multiple="true" break js maxsize validation 

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#657]
Mojarra 3.0.2
Omnifaces 4.0-M12
Tomcat 10.0.14
OpenJDK 17.0.1

JS size validation throws an Exception:

```
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "submittedValue" is null
	at org.omnifaces.component.input.InputFile.getConvertedValue(InputFile.java:339)
[...]
```

to reproduce:

```
<h:form id="multiple" enctype="multipart/form-data">
  <o:inputFile id="file" value="#{uploadImageTest.files}" multiple="true" accept="image/*" maxsize="#{ 100 * 1024 }" /> <!-- 100 Kb -->
  <h:message id="file_m" for="file" />
  <h:commandButton id="upload" value="Upload" action="#{uploadImageTest.uploadMultiple()}" />
</h:form>
```

```
@Named
@RequestScoped
public class UploadImageTest {

  private List<Part> files;
  public List<Part> getFiles() {return files;}
  public void setFiles(List<Part> files) {this.files = files;}

  public void uploadMultiple() {
    if (files != null) {
	    for (Part file : files) {
		    String name = Servlets.getSubmittedFileName(file);
		    String type = file.getContentType();
		    long size = file.getSize();
		    log.info("Uploaded file: {0} {1} {2}",name,type,size);
		    try {
			    InputStream content = file.getInputStream();
			    byte[] data = Utils.toByteArray(content);
			    log.info("Uploaded data {0} Kbyte" , data.length/1024  );
		    } catch (IOException e) {
			    e.printStackTrace();
		    }
	    }
      }
  }
}
```

**Comment by BalusC** [comment]
Norepro. 

Can you please include com.sun.faces and jakarta.faces lines in the stack trace?

**Comment by pizzi80** [comment]
Sorry about that, I thought that it was reproducible!

```
11:33:17,409 SEVERE [org.omnifaces.exceptionhandler.FullAjaxExceptionHandler logException] [0f7e4249-53c8-40be-aa62-a59ada331f21][127.0.0.1] FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/WEB-INF/errorpages/500.xhtml' will be shown.
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "submittedValue" is null
	at org.omnifaces.component.input.InputFile.getConvertedValue(InputFile.java:339)
	at jakarta.faces.component.UIInput.validate(UIInput.java:955)
	at jakarta.faces.component.UIInput.executeValidate(UIInput.java:1232)
	at jakarta.faces.component.UIInput.processValidators(UIInput.java:721)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:587)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:158)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1282)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1294)
	at jakarta.faces.component.UIForm.visitTree(UIForm.java:340)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1294)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1294)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:392)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:250)
	at jakarta.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:239)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
	at jakarta.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1252)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:49)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:681)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:133)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:117)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:184)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:141)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:127)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:84)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:439)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1641)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1147)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:321)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:449)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:385)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

11:33:17,412 INFO [com.sun.faces.renderkit.RenderKitUtils renderUnhandledMessages] WARNING: FacesMessage(s) have been enqueued, but may not have been displayed.
sourceId=multiple:file[severity=(ERROR 2), summary=(multiple:file: Size of file ''DSC_3977.jpg'' is larger than maximum of 100.0 KiB), detail=(multiple:file: Size of file ''DSC_3977.jpg'' is larger than maximum of 100.0 KiB)]
```

**Comment by BalusC** [comment]
Thanks to the stack trace I could nail down why exactly the code followed that unexpected path: it happens only if the `<o:inputFile>` has `required="true"` and the `web.xml` has context param `jakarta.faces.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE` set to `true`. 

Is this also the case in your actual code?

**Comment by BalusC** [comment]
I've at least fixed 2 corner cases found in the logic.

**Comment by pizzi80** [comment]
I never saw that param :sweat_smile: 

I think that the defaut value is true... btw probably it should be removed ... 

which is the case that a developer put required="true" on an input and JSF may skip validation? :face_with_head_bandage: 

this is my jsf conf:

```
<!-- JSF Configuration -->
<context-param>
    <param-name>jakarta.faces.FACELETS_BUFFER_SIZE</param-name>
    <param-value>131072</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.STATE_SAVING_METHOD</param-name>
    <param-value>server</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.PROJECT_STAGE</param-name>
    <param-value>Production</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.FACELETS_REFRESH_PERIOD</param-name>
    <param-value>1</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.FACELETS_SKIP_COMMENTS</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.VALIDATE_EMPTY_FIELDS</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
    <param-value>true</param-value>
</context-param>
<context-param>
    <param-name>jakarta.faces.DATETIMECONVERTER_DEFAULT_TIMEZONE_IS_SYSTEM_TIMEZONE</param-name>
    <param-value>true</param-value>
</context-param>
```

**Comment by BalusC** [comment]
Okay, jakarta.faces.VALIDATE_EMPTY_FIELDS has triggered it.

All clear now. Thank you for reporting this corner case!
