### ISSUE TITLE
validateBean and JDK 16+

### ISSUE THREAD

**Issue by balta3** [omnifaces/omnifaces#659]
When using JDK 16 or 17 the validateBean mode to validate a clone of the bean is not working correctly. The CloneCopier is not working because of an exception when calling the clone method:

```
Caused by: java.lang.IllegalStateException: Cannot invoke method 'clone' of class 'class x.y.z.MyClass' with arguments [].
     at org.omnifaces.util.Reflection.invokeMethod(Reflection.java:883)
     at org.omnifaces.util.Reflection.invokeMethod(Reflection.java:858)
     ... 163 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @37a8e57f
     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
     at org.omnifaces.util.Reflection.invokeMethod(Reflection.java:879)
     ... 164 more
```

I'm using omnifaces 3.11.2

**Comment by BalusC** [comment]
Actually, the setAccessible shouldn't need to be invoked there as that violates the contract of Cloneable#clone().

> By convention, classes that implement this interface should override
> {@code Object.clone} (which is protected) with a public method.
> See {@link java.lang.Object#clone()} for details on overriding this
> method.

**Comment by BalusC** [comment]
Can you please retry with 3.13-SNAPSHOT? https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/3.13-SNAPSHOT/

**Comment by BalusC** [comment]
3.13 has been released today nonetheless ;)
