### ISSUE TITLE
ArrayIndexOutOfBoundsException with /someurl?=

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#665]
Given any page with a o:form omnifaces throws an ArrayIndexOutOfBoundsException when URL is something like http://localhost/?=

I know this is not a correct url, but bots keep on trying URLs like this in our site and I can control it in an ExcepcionHandler, but it's kind of dirty.

Reproducer:
index.xhtml: 
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:o="http://omnifaces.org/ui">

<f:view contentType="text/html" transient="false">
    <h:body>
        <o:form/>
    </h:body>
</f:view>
</html>
```

URL: something like  http://localhost/?=  or  http://localhost/?myParam=123&=&anotherParam=x

Stacktrace: 
```
javax.servlet.ServletException: Index 0 out of bounds for length 0
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:403)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:327)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.omnifaces.util.Servlets.toParameterMap(Servlets.java:335)
	at org.omnifaces.util.Servlets.getRequestQueryStringMap(Servlets.java:241)
	at org.omnifaces.util.FacesLocal.getRequestQueryStringMap(FacesLocal.java:1116)
	at org.omnifaces.util.Components.getParams(Components.java:1248)
	at org.omnifaces.component.input.Form$ActionURLDecoratorViewHandler.getActionURL(Form.java:365)
	at org.apache.myfaces.renderkit.html.base.HtmlRenderer.getActionUrl(HtmlRenderer.java:78)
	at org.apache.myfaces.renderkit.html.base.HtmlFormRendererBase.getActionUrl(HtmlFormRendererBase.java:168)
	at org.apache.myfaces.renderkit.html.base.HtmlFormRendererBase.encodeBegin(HtmlFormRendererBase.java:71)
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:571)
	at org.omnifaces.component.input.Form.encodeBegin(Form.java:185)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:502)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:526)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:526)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1782)
```

Tested with myfaces 2.3-next and omnifaces 3.12, but I believe version should not matter.

I would suggest to do a defensive length check. Something like (but maybe prettier): 

```
    public static Map<String, List<String>> toParameterMap(String queryString) {
        String[] parameters = queryString.split(quote("&"));
        Map<String, List<String>> parameterMap = new LinkedHashMap<>(parameters.length);

        for (String parameter : parameters) {
            if (parameter.contains("=")) {
                String[] pair = parameter.split(quote("="));
                if (pair.length == 0) {
                    continue;
                }
                String key = decodeURL(pair[0]);
                String value = (pair.length > 1 && !isEmpty(pair[1])) ? decodeURL(pair[1]) : "";
                addParamToMapIfNecessary(parameterMap, key, value);
            }
        }

        return parameterMap;
    }
```

What do you think? Do you want a PR?

**Comment by BalusC** [comment]
Fixed and added to `TestServlets`. Thank you very much for reporting this issue!

**Comment by cocorossello** [comment]
Thanks!
