### ISSUE TITLE
MalformedInputException after upgrade 3.11.2 -> 3.12

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#667]
The stack trace I'm getting is not very useful I'm afraid:
```
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:813)
	at com.sun.faces.application.ByteArrayWebOutputStream.writeTo(ByteArrayWebOutputStream.java:91)
```
I'll try to get you a minimal reproducer.

**Comment by jepsar** [comment]
No reproducer yet, but when I disable the Gzip filter I'm getting (3.13):

```
java.lang.NullPointerException
	at org.omnifaces.util.FacesLocal.getRequest(FacesLocal.java:876)
	at org.omnifaces.cdi.viewscope.ViewScopeManager.isUnloadRequest(ViewScopeManager.java:225)
	at org.omnifaces.context.OmniExternalContext.getFlash(OmniExternalContext.java:70)
	at javax.faces.context.ExternalContextWrapper.getFlash(ExternalContextWrapper.java:1010)
```

**Comment by jepsar** [comment]
Just checked https://github.com/omnifaces/omnifaces/compare/3.11.2...3.12 and cannot find anything that could explain this issue. Will dig deeper and reopen this issue if needed.
