### ISSUE TITLE
ClassCastException when getting MethodReference

### ISSUE THREAD

**Issue by thomaswoeckinger** [omnifaces/omnifaces#677]
This issue is releated to #646.
In some rare cases a ClassCastException is thrown, because MethodExpressionValueExpressionAdapter can not be cast to the inner class ExpressionInspector$ValueExpressionType.

In line 135 of ExpressionInspector special handling for MethodExpressionValueExpressionAdapter is required.

I think it would be simple change because the variable fromMethod in line 139 will be true in such a case.

The whole stack trace below:

```
java.lang.ClassCastException: class org.omnifaces.el.MethodExpressionValueExpressionAdapter cannot be cast to class org.omnifaces.el.ExpressionInspector$ValueExpressionType (org.omnifaces.el.MethodExpressionValueExpressionAdapter and org.
omnifaces.el.ExpressionInspector$ValueExpressionType are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @781b4709)
        at org.omnifaces.el.ExpressionInspector.getMethodReference(ExpressionInspector.java:135) ~[omnifaces-3.13.jar:3.13]
        at org.omnifaces.el.MethodExpressionValueExpressionAdapter.getMethodInfo(MethodExpressionValueExpressionAdapter.java:75) ~[omnifaces-3.13.jar:3.13]
        at org.omnifaces.el.ExpressionInspector.getMethodReference(ExpressionInspector.java:178) ~[omnifaces-3.13.jar:3.13]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.sun.faces.lifecycle.Phase.handleAfterPhase(Phase.java:164) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:82) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.execute(DeltaSpikeLifecycleWrapper.java:89) ~[deltaspike-jsf-module-impl-1.9.5.jar:1.9.5]
        at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.16.jar:2.3.16]
        at jdk.internal.reflect.GeneratedMethodAccessor1639.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by BalusC** [comment]
Do you have a reproducer?

**Comment by thomaswoeckinger** [comment]
Currently only on a very special page, i will try to create a unit test

**Comment by BalusC** [comment]
That would be very helpful. I still can't come up with a test EL expression which could reproduce this issue.

**Comment by thomaswoeckinger** [comment]
> That would be very helpful. I still can't come up with a test EL expression which could reproduce this issue.

Test and fix is provided, let me know what you are thinking about it.

**Comment by thomaswoeckinger** [comment]
Unrelated to this issue but i had to change the scope of javaee-web-api from test to provided, otherwise i could not compile the code. Just to let you know

**Comment by BalusC** [comment]
Real issue has been identified and fixed in https://github.com/omnifaces/omnifaces/commit/9a17c514e96b42a88c36186071863a964c3fbb8f

IT has been extended with in total 3 new cases.

Thank you very much for reporting this issue and improving OmniFaces.
