### ISSUE TITLE
OmniViewHandler java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by granella** [omnifaces/omnifaces#682]
Application does not start on Wildfly 26.0.1

`22:57:25,775 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."app.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."app.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "app.war"
	at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:189)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: Failed to link org/omnifaces/viewhandler/OmniViewHandler (Module "deployment.app.war" from Service Module Loader): jakarta/faces/application/ViewHandlerWrapper
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:351)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:276)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:79)
	at org.jboss.modules.Module.loadModuleClass(Module.java:753)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:192)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.jsf@26.0.1.Final//org.jboss.as.jsf.deployment.JSFComponentProcessor.installJsfArtifactComponent(JSFComponentProcessor.java:412)
	at org.jboss.as.jsf@26.0.1.Final//org.jboss.as.jsf.deployment.JSFComponentProcessor.processJSFArtifactsForInjection(JSFComponentProcessor.java:297)
	at org.jboss.as.jsf@26.0.1.Final//org.jboss.as.jsf.deployment.JSFComponentProcessor.deploy(JSFComponentProcessor.java:244)
	at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
	... 8 more`

**Comment by melloware** [comment]
Are you using OmniFaces 3.x or 4.x?   You need to use the correct version based on EE level. OmniFaces 3.x is for javax.faces and 4.x is for Jakarta.faces

It looks like you are using 4.x but need to be using 3.x?

**Comment by granella** [comment]
I'm using the version 4.0-M13

**Comment by BalusC** [comment]
https://www.wildfly.org/downloads/

![image](https://user-images.githubusercontent.com/173372/164892206-9ece01d9-80a5-487a-afe4-6bb77aeaf3d7.png)

If you're using "**Jakarta EE 8 Full & Web Distribution**" then you still need OmniFaces 3.x for `javax.faces`.
Only if you're using "**WildFly Preview EE 9.1 Distribution**" then you can use OmniFaces 4.x for `jakarta.faces`.
