### ISSUE TITLE
UnmappedResourceHandler NPE when asking for directories instead of file

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#685]
Mojarra 3.0.2 / OmniFaces v4 latest / Tomcat 10.0.20

Suppose to have a css static file inside **/resources/css** called _style.css_

everything works for normal usage, eg. 

`http://localhost/<context-path>/jakarta.faces.resource/css/style.css`

but if I do a GET request to the parent folder ( ... a lot of bots likes to play with this kind of requests :D )

`http://localhost/<context-path>/jakarta.faces.resource/css`
`http://localhost/<context-path>/jakarta.faces.resource/css/`

I got the following exception:

```
15:13:34.872 ERROR [StandardWrapperValve] Servlet.service() for servlet [FacesServlet] in context with path [/booq] threw exception
java.lang.NullPointerException: Cannot read field "name" because "other" is null
	at com.sun.faces.application.resource.LibraryInfo.<init>(LibraryInfo.java:53)
	at com.sun.faces.application.resource.ResourceInfo.<init>(ResourceInfo.java:51)
	at com.sun.faces.application.resource.ClientResourceInfo.<init>(ClientResourceInfo.java:98)
	at com.sun.faces.application.resource.ResourceHelper.getInputStream(ResourceHelper.java:136)
	at com.sun.faces.application.resource.ResourceImpl.getInputStream(ResourceImpl.java:152)
	at org.omnifaces.resourcehandler.RemappedResource.getInputStream(RemappedResource.java:114)
	at org.omnifaces.resourcehandler.UnmappedResourceHandler.handleResourceRequest(UnmappedResourceHandler.java:164)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:678)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:133)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:117)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:85)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:661)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:439)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:867)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1652)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1155)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:326)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:460)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:396)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

With the standard configuration of UnmappedResourceHandler

**web.xml**
```
 <servlet-mapping>
    <servlet-name>FacesServlet</servlet-name>
    <url-pattern>*.xhtml</url-pattern>
    <url-pattern>/jakarta.faces.resource/*</url-pattern> <!-- Omnifaces UnMappedResourceHandler -->
</servlet-mapping>
```

**faces-config.xml**
```
<application>
    ...
  <resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>
</application>

```

**Comment by BalusC** [comment]
Fixed in 2.x and onwards. Thank you for reporting this issue and improving OmniFaces!
