### ISSUE TITLE
o:importConstants broken in 3.13.1

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#687]
I just upgraded to 3.13.1 and I noticed a bug in o:importConstants

`<o:importConstants type="com.MyEnum">
`
`public enum MyEnum implements Serializable {
...`

When the enum implements any interface then importConstants fails with: 

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.omnifaces.taghandler.ImportConstants.getDeclaredTypes(ImportConstants.java:174)
	at org.omnifaces.taghandler.ImportConstants.collectConstants(ImportConstants.java:151)
	at org.omnifaces.taghandler.ImportConstants.apply(ImportConstants.java:126)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
```

**Comment by BalusC** [comment]
That was awkward. 3.13.2 and 4.0-M15 have just been released with the fix. Version 2.7.17 which didn't use streams was unaffected.

Thank you very much for reporting this issue!

**Comment by cocorossello** [comment]
Hi, Thanks for fixing this.

I think I've found another problem when using it with an interface;
                        <o:importConstants type="javax.servlet.RequestDispatcher"/>

It probably does not work for interfaces as superclass is null. Probably a null check is needed
```

	private static void fillAllSuperClasses(Class<?> type, Set<Class<?>> set) {
		for (Class<?> sc = type.getSuperclass(); sc != Object.class && sc != null; sc = sc.getSuperclass()) {
			set.add(sc);
		}
	}

```

Want a PR or a new issue?

**Comment by BalusC** [comment]
Fixed now. Will release later.
