### ISSUE TITLE
SAXParseException faces-config

### ISSUE THREAD

**Issue by ymnrad2015** [omnifaces/omnifaces#689]
When we restart the Tomcat server we get the following error message. Could you give us a suggestion

`com.sun.faces.config.ConfigurationException: java.util.concurrent.ExecutionException: com.sun.faces.config.ConfigurationException: Unable to parse document 'jar:file:/var/lib/tomcat_1/webapps/rp_web/WEB-INF/lib/omnifaces-3.12.jar!/META-INF/faces-config.xml': org.xml.sax.SAXParseException; lineNumber: 1664; columnNumber: 40; InvalidRegex: Musterwert '([a-z]{2})[_|\-]?([\p{L}]{2})?[_|\-]?(\w+)?' ist kein gültiger regulärer Ausdruck. Der gemeldete Fehler war: 'Unbekannte Eigenschaft.' bei Spalte '{2}'.
	at com.sun.faces.config.manager.Documents.getXMLDocuments(Documents.java:115)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:267)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:207)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5125)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5643)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: com.sun.faces.config.ConfigurationException: Unable to parse document 'jar:file:/var/lib/tomcat_1/webapps/rp_web/WEB-INF/lib/omnifaces-3.12.jar!/META-INF/faces-config.xml': org.xml.sax.SAXParseException; lineNumber: 1664; columnNumber: 40; InvalidRegex: Musterwert '([a-z]{2})[_|\-]?([\p{L}]{2})?[_|\-]?(\w+)?' ist kein gültiger regulärer Ausdruck. Der gemeldete Fehler war: 'Unbekannte Eigenschaft.' bei Spalte '{2}'.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.sun.faces.config.manager.Documents.getXMLDocuments(Documents.java:113)
	... 15 more
Caused by: com.sun.faces.config.ConfigurationException: Unable to parse document 'jar:file:/var/lib/tomcat_1/webapps/rp_web/WEB-INF/lib/omnifaces-3.12.jar!/META-INF/faces-config.xml': org.xml.sax.SAXParseException; lineNumber: 1664; columnNumber: 40; InvalidRegex: Musterwert '([a-z]{2})[_|\-]?([\p{L}]{2})?[_|\-]?(\w+)?' ist kein gültiger regulärer Ausdruck. Der gemeldete Fehler war: 'Unbekannte Eigenschaft.' bei Spalte '{2}'.
	at com.sun.faces.config.manager.tasks.ParseConfigResourceToDOMTask.call(ParseConfigResourceToDOMTask.java:154)
	at com.sun.faces.config.manager.tasks.ParseConfigResourceToDOMTask.call(ParseConfigResourceToDOMTask.java:68)
	... 4 more
Caused by: com.sun.faces.config.ConfigurationException: org.xml.sax.SAXParseException; lineNumber: 1664; columnNumber: 40; InvalidRegex: Musterwert '([a-z]{2})[_|\-]?([\p{L}]{2})?[_|\-]?(\w+)?' ist kein gültiger regulärer Ausdruck. Der gemeldete Fehler war: 'Unbekannte Eigenschaft.' bei Spalte '{2}'.
	at com.sun.faces.config.manager.DbfFactory.loadSchema(DbfFactory.java:778)
	at com.sun.faces.config.manager.DbfFactory.getSchema(DbfFactory.java:586)
	at com.sun.faces.config.manager.tasks.ParseConfigResourceToDOMTask.getDocument(ParseConfigResourceToDOMTask.java:251)
	at com.sun.faces.config.manager.tasks.ParseConfigResourceToDOMTask.call(ParseConfigResourceToDOMTask.java:144)
	... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1664; columnNumber: 40; InvalidRegex: Musterwert '([a-z]{2})[_|\-]?([\p{L}]{2})?[_|\-]?(\w+)?' ist kein gültiger regulärer Ausdruck. Der gemeldete Fehler war: 'Unbekannte Eigenschaft.' bei Spalte '{2}'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:395)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4153)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4136)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.reportSchemaError(XSDAbstractTraverser.java:720)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDSimpleTypeTraverser.getSimpleType(XSDSimpleTypeTraverser.java:405)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDSimpleTypeTraverser.traverseSimpleTypeDecl(XSDSimpleTypeTraverser.java:162)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDSimpleTypeTraverser.traverseGlobal(XSDSimpleTypeTraverser.java:103)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseGlobalDecl(XSDHandler.java:1896)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1781)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseSimpleContent(XSDComplexTypeTraverser.java:428)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:303)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:190)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1435)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:634)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:609)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:568)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:534)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:253)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at com.sun.faces.config.manager.DbfFactory.loadSchema(DbfFactory.java:716)
	... 8 more
`

**Comment by melloware** [comment]
i see you are using 3.12 do you get the same error on 3.13.2 ?

**Comment by BalusC** [comment]
There's something odd going on.

> lineNumber: 1664

[It has only 59 lines](https://github.com/omnifaces/omnifaces/blob/3.12/src/main/resources/META-INF/faces-config.xml).

**Comment by ymnrad2015** [comment]
> There's something odd going on.
> 
> > lineNumber: 1664
> 
> [It has only 59 lines](https://github.com/omnifaces/omnifaces/blob/3.12/src/main/resources/META-INF/faces-config.xml).

that surprised me too. So I couldn't understand what it could be.
I don't know what's going on.

**Comment by ymnrad2015** [comment]
> i see you are using 3.12 do you get the same error on 3.13.2 ?

I updated it. I want to test it soon

**Comment by BalusC** [comment]
Can you at least change your JVM locale to English? That will yield exception messages   which are so much better Googleable.

This is the closest I could find: https://bugs.openjdk.java.net/browse/JDK-8198548 

Which Java version are you running?

**Comment by ymnrad2015** [comment]
> Can you at least change your JVM locale to English? That will yield exception messages which are so much better Googleable.
> 
> This is the closest I could find: https://bugs.openjdk.java.net/browse/JDK-8198548
> 
> Which Java version are you running?

Java Version openjdk version "1.8.0_302"

Ok i will change it

**Comment by BalusC** [comment]
It's been a while already. Do you have any updates or at least a reproducer?

**Comment by BalusC** [comment]
Closing off as norepro.
