### ISSUE TITLE
o:form URLDecoder: Incomplete trailing escape (%) pattern

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#718]
Hi,

Given any URL like https://showcase.omnifaces.org/?whatever=% an error is thrown if it's an o:form with includeRequestParams: 

```
Caused by: java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:232)
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:149)
	at org.omnifaces.util.Utils.decodeURL(Utils.java:1188)
	at org.omnifaces.util.Servlets.toParameterMap(Servlets.java:359)
	at org.omnifaces.util.Servlets.getRequestQueryStringMap(Servlets.java:246)
	at org.omnifaces.util.FacesLocal.getRequestQueryStringMap(FacesLocal.java:1156)
	at org.omnifaces.util.Components.getParams(Components.java:1253)
	at org.omnifaces.component.input.Form$ActionURLDecoratorViewHandler.getActionURL(Form.java:365)
```

It's an incorrect URL, but bots (and also some users) keep on trying this kind of stuff.

Maybe a solution could be to skip a possible trailing %?

(tested with omnifaces 3.14, but should be the same in 4.0)

WDYT?

**Comment by BalusC** [comment]
It should indeed be more lenient.

**Comment by cocorossello** [comment]
Thank you!
