### ISSUE TITLE
java.lang.StackOverflowError in BeansLocal.destroy

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#719]
Sometimes I see this problem in my logs (OF v3.14):
```
Caused by: java.lang.StackOverflowError
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
        at org.omnifaces.util.BeansLocal.destroy(BeansLocal.java:243)
```

in my case the destroyed class is 

```
@Specializes
@SessionScoped
public class WindowContextQuotaHandler extends JsfWindowContextQuotaHandler
```
        
but the problem is clearly visible at BeansLocal.java:243

**Comment by BalusC** [comment]
Oh wow that was regression of #673 
https://github.com/omnifaces/omnifaces/commit/c39c3a69ac13027e9d5ddace0bae403c5d27824c#diff-301a1a376af29d57008b4f67b4e6159372b9ff684eac5cdc9be00f88f3ca1631L226

Apparently the Eclipse 'Save Actions' configuration option 'Remove unnecessary array creation' was responsible for this behavior :/
