### ISSUE TITLE
Internal server error when using extensionless urls with combined resource handler

### ISSUE THREAD

**Issue by dajevtic** [omnifaces/omnifaces#728]
Using omnifaces 4.0.1 on Wildfly 27.0.1 Jakarta Preview, when activating extensionless mapping:
`
<context-param>
        <param-name>jakarta.faces.AUTOMATIC_EXTENSIONLESS_MAPPING</param-name>
        <param-value>true</param-value>
</context-param>
`

AND in combination with Combined Resource handler:
`<resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>`

and navigating to the page without extension, I am getting the following error and page displays the default 500 code error page:

Error Rendering View[/index.xhtml]: java.lang.StringIndexOutOfBoundsException: begin -1, end 6, length 6
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at java.base/java.lang.String.substring(String.java:2680)
	at deployment.demo.war//org.omnifaces.util.FacesLocal.getMapping(FacesLocal.java:232)
	at deployment.demo.war//org.omnifaces.util.Faces.getMapping(Faces.java:396)
	at deployment.demo.war//org.omnifaces.resourcehandler.DynamicResource.getRequestPath(DynamicResource.java:73)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.renderkit.html_basic.ScriptStyleBaseRenderer.encodeEnd(ScriptStyleBaseRenderer.java:213)
	at jakarta.faces.api//jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:586)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1442)
	at deployment.demo.war//org.primefaces.renderkit.HeadRenderer.encodeBegin(HeadRenderer.java:121)
	at jakarta.faces.api//jakarta.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:531)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1432)
	at jakarta.faces.api//jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:162)
	at jakarta.faces.api//jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at jakarta.faces.api//jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at deployment.demo.war//org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:151)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:172)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.smallrye.opentracing-contrib//io.smallrye.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:69)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.demo.war//org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
	at deployment.demo.war//org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)

**Comment by BalusC** [comment]
Fixed, than you very much for reporting.

**Comment by dajevtic** [comment]
Thank you for the great library

**Comment by dajevtic** [comment]
I am a little tempted to reopen this issue. The stacktrace has gone away, however the combined resource handler does not seem to return all resources as expected when using extensionless mapping.

Using: http://localhost:8080/demo/index.html (html is my default extension, but could be jsf or any other as well):
<img width="677" alt="Bildschirm­foto 2023-01-06 um 21 27 31" src="https://user-images.githubusercontent.com/9357311/211094163-3e8509d1-2c4d-4573-b242-ce25f4d2dd56.png">

Using extensionless on url: Using: http://localhost:8080/demo/index I get:

<img width="676" alt="Bildschirm­foto 2023-01-06 um 21 28 32" src="https://user-images.githubusercontent.com/9357311/211094398-38e9f6d2-968d-4a66-99c0-62e00e42354c.png">

**Comment by dajevtic** [comment]
@BalusC Could you please recheck if this issue is truly resolved. Thank you very much. Using github 4.1-SNAPSHOT incl. your commit Fix #728
