### ISSUE TITLE
Deployment Exception on WildFly 27 with OmniFaces 4.1 due to DateProducer

### ISSUE THREAD

**Issue by mkomko** [omnifaces/omnifaces#741]
We upgraded our dependency from OmniFaces 4.0.1 to OmniFaces 4.1 and now receive the following exception during the deployment of our JSF application:
```
10:18:56,337 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."tenfold.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."tenfold.ear".WeldStartService: Failed to start service
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name now resolves to beans: [Producer Method [TemporalDate] with qualifiers [@Default @Any @Named] declared as [[BackedAnnotatedMethod] @Produces @Named @RequestScoped public org.omnifaces.cdi.config.DateProducer.getNow()], Producer Method [TemporalDate] with qualifiers [@Default @Any @Named] declared as [[BackedAnnotatedMethod] @Produces @Named @RequestScoped public org.omnifaces.cdi.config.DateProducer.getNow()]]
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bootstrap.Validator.validateBeanName(Validator.java:642)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bootstrap.ConcurrentValidator$5.doWork(ConcurrentValidator.java:121)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bootstrap.ConcurrentValidator$5.doWork(ConcurrentValidator.java:119)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

Thanks in advance!

**Comment by BalusC** [comment]
Norepro.

This can happen when you have multiple OmniFaces libraries in the runtime classpath.

Likely your build and/or (hot)deployment was dirty. Clean and repeat. In case of WildFly that also includes trashing the contents of standalone/tmp folder.

**Comment by mkomko** [comment]
@BalusC Sorry about that, it really must have been the standalone\tmp directory :-(. Thanks!
