### ISSUE TITLE
Beans.xml: Discovery Mode

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#744]
This came up due to a Quarkus warning with 4.1.  It says that a beans.xml was discovered using "all" discovery mode and it should be "annotated".   Basically only classes with proper annotations should be scanned. 

I am sure you made "all" intentional but I thought I would raise it here to get your thoughts.

**Comment by melloware** [comment]
We resolved it on the Quarkus end: https://github.com/quarkusio/quarkus/issues/31378

Nevermind!

**Comment by BalusC** [comment]
Should indeed be `annotated`. OmniFaces doesn't have any non-annotated bean which should be a CDI managed bean. It was set to `all` to work around a Tomcat+Weld bug: https://github.com/omnifaces/omnifaces/commit/9193db482b90a5de30590d3d7316acb4951d3da5

I'd like to revise it.

**Comment by melloware** [comment]
Awesome!

**Comment by pizzi80** [comment]
just to let you know that Weld 5 on Tomcat 10.1 works flawlessly with `annotated`

**Comment by melloware** [comment]
@BalusC sorry to bother you here but I noticed my fork of Omnifaces does not contain the 4.X branch.  I have looked everywhere for instructions on how to update my fork to pull in new branches from upstream but everything I have tried is not working. Any advice?  It seems I have the same issue with my Mojarra fork?

**Comment by melloware** [comment]
Nevermind I figured it out.

**Comment by BalusC** [comment]
Deploys fine with Weld 3.0.0.Final (2017), so I'll apply change on 2.x as well.

**Comment by melloware** [comment]
Thanks!

**Comment by BalusC** [comment]
`DateProducer` (`#{now}` and `#{startup}`) failed since this change, it has been fixed.

`@Eager` failed in Payara server since this change (but works in all other servers), still analyzing it.

**Comment by BalusC** [comment]
Ok all tests now pass on 2.x 3.x 4.x.

**Comment by mkomko** [comment]
When upgrading from OmniFaces 4.1 to 4.2 (or 4.3) in our application (WildFly 30, MyFaces 4.0.1), we get the following errors due to this change:
```
Caused by: jakarta.faces.FacesException: Could not find any registered converter-class by converterId : omnifaces.SelectItemsConverter
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.application.ApplicationImpl.createConverter(ApplicationImpl.java:1357)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:160)
	at deployment.ourapp.ear.ourapp-web.war//org.omnifaces.cdi.converter.ConverterManager.createConverter(ConverterManager.java:127)
	at deployment.ourapp.ear.ourapp-web.war//org.omnifaces.cdi.converter.ConverterManager$Proxy$_$$_WeldClientProxy.createConverter(Unknown Source)
	at deployment.ourapp.ear.ourapp-web.war//org.omnifaces.application.OmniApplication.createConverter(OmniApplication.java:72)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.tag.faces.ValueHolderRule$LiteralConverterMetadata.applyMetadata(ValueHolderRule.java:51)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.tag.MetadataImpl.applyMetadata(MetadataImpl.java:45)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.MetaTagHandler.setAttributes(MetaTagHandler.java:63)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.setAttributes(DelegatingMetaTagHandler.java:93)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:281)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:52)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:57)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:362)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:52)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:57)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.tag.faces.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:362)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:52)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:67)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:47)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:49)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:195)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.buildView(FaceletViewDeclarationLanguage.java:423)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:83)
	at jakarta.faces.impl:myfaces@4.0.1//org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:241)
	at jakarta.faces.api:myfaces@4.0.1//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:225)
```

We are using the following in the `web.xml`:
```
    <context-param>
        <param-name>org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING</param-name>
        <param-value>true</param-value>
    </context-param>
```

But the error also appears with the value set to _false_.

When manually changing the _bean-discovery-mode_ back to `all` in the `omnifaces-4.3.jar` it works without error.

@BalusC Do you want me to create a new issue or do you want to do it or do you want to use this one? Thank you very much in advance!

**Comment by melloware** [comment]
@mkomko could this be  MyFaces bug?  Have you tried it with Mojarra?

**Comment by mkomko** [comment]
@melloware It could be, although I thought CDI would be responsible for scanning for annotations. But when using the primefaces-test project, it only happens when using MyFaces and said context-param. Should I file a MyFaces bug instead?

**Comment by melloware** [comment]
I think so I don't think this is related to OmniFaces and the bean discovery mode is correct according to BalusC and Quarkus. It was "all" to workaround an old Tomcat issue.

I would open a MyFaces ticket with PrimeFaces Test reproducer showing the issue.

**Comment by mkomko** [comment]
Done: https://issues.apache.org/jira/browse/MYFACES-4643

**Comment by mkomko** [comment]
@melloware @BalusC The MyFaces ticket was closed. Do you have any advice?

When disabling USE_CDI_FOR_ANNOTATION_SCANNING and relying on the default implementation, it might be not working because of the following:

When debugging the MyFaces _DefaultAnnotationProvider_ the method _getAnnotatedMetaInfClasses_ receives the following URLs, which are definitely wrong (the directory _bin\content_ does not exist). But these are the URLs returned by the ModuleClassLoader?
```
0 = {URL@44555} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/rewrite-config-prettyfaces-10.0.0.Final.jar/META-INF/faces-config.xml"
1 = {URL@44556} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/primefaces-extensions-13.0.3-jakarta.jar/META-INF/faces-config.xml"
2 = {URL@44557} "jar:file:/C:/ourapp/server/modules/org/jboss/as/jsf-injection/myfaces/wildfly-jsf-injection-30.0.0.Final.jar!/META-INF/faces-config.xml"
3 = {URL@44558} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/primefaces-13.0.3-jakarta.jar/META-INF/faces-config.xml"
4 = {URL@44559} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/rain-theme-4.0.0-jakarta.jar/META-INF/faces-config.xml"
5 = {URL@44560} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/omnifaces-4.3.jar/META-INF/faces-config.xml"
6 = {URL@44561} "vfs:/C:/ourapp/server/bin/content/ourapp.ear/ourapp-web.war/WEB-INF/lib/rewrite-integration-faces-10.0.0.Final.jar/META-INF/faces-config.xml"
```

**Comment by mkomko** [comment]
That's what tandraschko wrote:
> OmniFaces could just add a "bean defining annotation" to it (check CDI spec) or omnifaces / your application must set bean-discovery-mode=all. Anyway, its just a CDI problem or configuration, we cant help here.

> TBH i wont invest many time here. MF5.0 will rely on CDI scanning only. i would try to fix your setup here or ask OmniFaces guys to add e.g. @ApplicationScoped.

**Comment by BalusC** [comment]
Oh? These are already annotated with `@FacesConverter`. But technically speaking `@FacesConverter` is indeed not a CDI bean defining annotation (yet?), it's a "plain" JSF annotation. Same applies to `@FacesValidator`, `@FacesRenderer`, `@FacesComponent`, etc. This means that MyFaces 4 is not backwards compatible for these and that component library developers either need to add a CDI bean defining annotation on them, or to re-register them in `faces-config.xml` so it can be found over there.

I'll this weekend look what I can do from OmniFaces `ConverterManager` on. All these converters (fortunately) have an easy to recognize `omnifaces.` prefix in the converter ID. But please open a new issue with a link to current issue :)

**Comment by tandraschko** [comment]
first of all, `org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING=true` is actually https://github.com/jakartaee/faces/issues/1584, and a optional feature to speed up perf

@mkomko mixes 2 issues:
1) `USE_CDI_FOR_ANNOTATION_SCANNING=true` doesnt collect OmniFaces converters; thats because FacesConverter is not a bean defining annotation and you switched to `annotated`. OmniFaces could fix it by adding `@ApplicationScoped` or adding the converter as bean via a CDI Extension
2) the DefaultAnnotationProvider (`USE_CDI_FOR_ANNOTATION_SCANNING=false`) doesnt find the OmniFaces converter. This could be a MyFaces bug of our classpath scanning which is broken in newer Wildfly, Jakarta or Java versions? Not sure; i can give some advices here but im not a wildfly user and wont invest mouch time here as hopefully  https://github.com/jakartaee/faces/issues/1584 will be the future.

**Comment by mkomko** [comment]
@tandraschko Thank you for clearing that up, I was indeed not clear above that I was now writing about the "default" implentation. I edited my comment.

@BalusC Thank you, I created the new issue. If you need anything let me know.
