### ISSUE TITLE
Problem with javax.xml

### ISSUE THREAD

**Issue by zakhdar** [omnifaces/omnifaces#746]
Dear, 

I have a problem on a Quarkus/MyFaces project, I think it is a conflict of dependence with the dynamicsreport library (https://github.com/dynamicreports/dynamicreports) that I use to generate reports in my application.

The simple fact of including this library in my pom prevents the launching of the application with the following error.
```
<dependency>
   <groupId>net.sourceforge.dynamicreports</groupId>
   <artifactId>dynamicreports-core</artifactId>
   <version>6.12.1</version>
</dependency>
```
StackTrace : 

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 15 more
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
	at org.omnifaces.util.Xml.createDocumentBuilder(Xml.java:83)
	at org.omnifaces.util.Xml.createDocument(Xml.java:70)
	at org.omnifaces.util.Xml.getNodeTextContents(Xml.java:176)
	at org.omnifaces.facesviews.FacesViews.scanAndStoreWelcomeFiles(FacesViews.java:447)
	at org.omnifaces.facesviews.FacesViews.registerForwardingFilter(FacesViews.java:278)
	at org.omnifaces.ApplicationInitializer.onStartup(ApplicationInitializer.java:66)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:580)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:251)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:521)
	at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy_16(Unknown Source)
	at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy(Unknown Source)
	... 16 more
```
Could you suggest me which lib could cause this problem, I did not find any lib in common

The environment I use is the following : 
Java : registry.access.redhat.com/ubi9/openjdk-17:1.14  (App run on kubernetes)
omnifaces-quarkus.version = 3.14.2
primefaces-quarkus.version = 2.12.2
myfaces.version = 2.3-next-SNAPSHOT
quarkus.version = 2.16.4.Final

Thank you in advance for your help

**Comment by melloware** [comment]
This is not an OmniFaces issue its a Quarkus issue.  This is similar to why I had to remove the FeedReader component from Primefaces.

What is happening is check your `mvn dependency:tree` and you will see either that lib or some lib its using is bringing in a legacy XML library like `xalan` or `JDOM` or some other library that is not Quarkus Native friendly.

You can try finding that library and excluding it.

**Comment by BalusC** [comment]
Indeed. OmniFaces does not have any JAXB implementation as dependency. Instead, it relies on that the JAXB implementation is already provided by the target runtime. Namely, any sane JEE application server already provides it out the box as well as many servletcontainers. Bringing another JAXB implementation along would only cause conflicts.

Do note that the JAXB API itself is defined in Java SE, not in Java EE/Jakarta EE.
