### ISSUE TITLE
PWA view root null with UnmappedResourceHandler active

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#765]
If I remove the `UnmappedResourceHandler` it works

Faces **4.0.2** or **4.1.0-SNAPSHOT**
OmniFaces 4.2
Tomcat 10.1.10
Java 17.0.7

**web.xml**
```
<servlet-mapping>
  <servlet-name>FacesServlet</servlet-name>
  <url-pattern>*.xhtml</url-pattern>
  <url-pattern>/jakarta.faces.resource/*</url-pattern> 	<!-- Omnifaces UnMappedResourceHandler -->
</servlet-mapping>
```

**faces-config.xml**

```
<application>
  <resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler> 
</application>
```

**Java**
```
@ApplicationScoped
public class PWA extends WebAppManifest {

    static final String name = "Playground";
    static final String color = "#414141";

    @Override public String getName() {return name;}
    @Override public String getShortName() {return name;}
    @Override public String getThemeColor() {return color;}

    @Override
    public Collection<ImageResource> getIcons() {
        return List.of();
    }

}
```

**Exception during page load**
```
java.lang.NullPointerException: Cannot invoke "jakarta.faces.component.UIViewRoot.getComponentResources(jakarta.faces.context.FacesContext)" because the return value of "jakarta.faces.context.FacesContext.getViewRoot()" is null
	at org.omnifaces.util.Components.addScriptResourceToTarget(Components.java:796)
	at org.omnifaces.util.Components.addScriptResourceToHead(Components.java:814)
	at org.omnifaces.util.Components.addScriptResource(Components.java:765)
	at org.omnifaces.util.Components.addFacesScriptResource(Components.java:783)
	at org.omnifaces.resourcehandler.PWAResourceHandler.decorateResource(PWAResourceHandler.java:337)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:79)
	at org.omnifaces.util.FacesLocal.createResource(FacesLocal.java:468)
	at org.omnifaces.resourcehandler.UnmappedResourceHandler.createResource(UnmappedResourceHandler.java:253)
	at org.omnifaces.resourcehandler.UnmappedResourceHandler.handleResourceRequest(UnmappedResourceHandler.java:158)
	at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:166)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:688)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:597)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:429)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1664)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1234)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:328)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:468)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:404)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BalusC** [comment]
Reproduced.

**Comment by BalusC** [comment]
Fixed, thank you very much for reporting this issue and improving OmniFaces!
