### ISSUE TITLE
ToCollectionConverter with List of Enum

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#816]
Mojarra 4.0.7
OmniFaces 4.4.1
Tomcat 10.1.23
Java 21.0.3

If I excplicitly set `itemConverter="jakarta.faces.Enum"` 
I got `jakarta.faces.FacesException: Expression Error: Named Object: jakarta.faces.Enum not found`
(see below the full stacktrace)

the same goes to the other side of conversion with some `h:input` `h:select`

is it a Mojarra bug ... ?

```
@Named
@RequestScoped
public class TestViewAction implements Serializable {

    @Serial private static final long serialVersionUID = -8320082942764680795L
   
    public enum TestEnum { A,B,C }

    private List<TestEnum> enums;
    public List<TestEnum> getEnums() {return enums;}
    public void setEnums(List<TestEnum> enums) {this.enums = enums;}

    @PostConstruct
    public void init() {
        enums = List.of( TestEnum.A, TestEnum.B );
    }

}
```

```
<h:outputText value="#{testViewAction.enums}">
    <o:converter converterId="omnifaces.ToCollectionConverter" itemConverter="jakarta.faces.Enum" />
</h:outputText>
```

```
jakarta.servlet.ServletException: Expression Error: Named Object: jakarta.faces.Enum not found.
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:709)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:196)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:187)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:144)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:130)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:86)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:597)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1685)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1269)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:330)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:470)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:406)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: jakarta.faces.FacesException: Expression Error: Named Object: jakarta.faces.Enum not found.
	at com.sun.faces.util.Util.notNullNamedObject(Util.java:518)
	at com.sun.faces.application.applicationimpl.InstanceFactory.createConverter(InstanceFactory.java:418)
	at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:475)
	at jakarta.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:335)
	at org.omnifaces.cdi.converter.ConverterManager.createConverter(ConverterManager.java:127)
	at org.omnifaces.cdi.converter.ConverterManager$Proxy$_$$_WeldClientProxy.createConverter(Unknown Source)
	at org.omnifaces.application.OmniApplication.createConverter(OmniApplication.java:72)
	at org.omnifaces.util.FacesLocal.createConverter(FacesLocal.java:375)
	at org.omnifaces.util.FacesLocal.createConverter(FacesLocal.java:357)
	at org.omnifaces.util.Faces.createConverter(Faces.java:586)
	at org.omnifaces.converter.ToCollectionConverter.getAsString(ToCollectionConverter.java:136)
	at org.omnifaces.converter.ToCollectionConverter.getAsString(ToCollectionConverter.java:73)
	at org.omnifaces.taghandler.Converter$DeferredConverter.getAsString(Converter.java:178)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getFormattedValue(HtmlBasicRenderer.java:449)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getFormattedValue(HtmlBasicRenderer.java:463)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:135)
	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:585)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1442)
	at jakarta.faces.render.Renderer.encodeChildren(Renderer.java:146)
	at jakarta.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:556)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1438)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:449)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:160)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:166)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:150)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	... 33 more
```

**Comment by BalusC** [comment]
`jakarta.faces.Enum` converter is a special one which requires being instantiated by constructor with the desired enum type passed.

Have you tried `omnifaces.GenericEnumConverter` instead?

**Comment by pizzi80** [comment]
> being instantiated by constructor

ok! now it's clear !!!!

> Have you tried omnifaces.GenericEnumConverter instead?

Yes, it works but it creates a new ViewScope 
which is not good for a stateless view  
`<f:view transient="true" ... />` 

while if I use the `omnifaces.GenericEnumConverter` 
to convert an `o:inputHidden` it doesn't works at all 

but I found an S.O. question where you have just answered that is not compatible

**Comment by pizzi80** [comment]
I was only playing with all possible scenario 

whit List of Enum conversion 
on a stateless view (which is a pain with a lot of gotchas)

probably the new version of your book should cover
the interaction with a stateless view  
in a special section 

I'm trying to push this situation to the limit 
also with ajax, complex model conversion, 
valueChangeListeners and dynamic page re-rendering 

There a lot of things involved ....

**Comment by BalusC** [comment]
> Yes, it works but it creates a new ViewScope which is not good for a stateless view <f:view transient="true" ... />

Fair point. I should probably add a predefined attribute which could then represent the FQN of the enum.
