### ISSUE TITLE
Quarkus: OmniFaces 4.5 breaks build

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#831]
Build failure is here: https://github.com/quarkiverse/quarkus-omnifaces/actions/runs/10662247874/job/29549102762

It seems related to the `FacesConfigXmlSingleton` change to get the ExceptionHandlerFactories.

```
Caused by: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:110)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:184)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:604)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:251)
	... 9 more
Caused by: java.lang.ExceptionInInitializerError
	at org.omnifaces.config.FacesConfigXml.instance(FacesConfigXml.java:66)
	at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.registerFacesExceptionFilterIfNecessary(FullAjaxExceptionHandler.java:332)
	at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:95)
	... 16 more
Caused by: java.lang.IllegalStateException: FacesConfigXml failed to initialize. Perhaps your faces-config.xml contains a typo?
	at org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:108)
	at org.omnifaces.config.FacesConfigXmlSingleton.<clinit>(FacesConfigXmlSingleton.java:60)
	... 19 more
Caused by: jakarta.enterprise.inject.CreationException: Null contextual instance was produced by a normal scoped synthetic bean: SYNTHETIC bean [class=jakarta.servlet.ServletContext, id=CYpq0iv9Pf0bdpqTn39pTx7xoyM]
	at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.doCreate(Unknown Source)
	at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.create(Unknown Source)
	at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c20(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at org.omnifaces.util.BeansLocal.getInstance(BeansLocal.java:131)
	at org.omnifaces.util.BeansLocal.getInstance(BeansLocal.java:121)
	at org.omnifaces.util.BeansLocal.getInstance(BeansLocal.java:113)
	at org.omnifaces.util.Servlets.getContext(Servlets.java:812)
	at org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:99)
```

**Comment by BalusC** [comment]
Wondering how it's different from FacesConfigXml#getResourceHandlers() / FacesConfigXmlSingleton#parseResourceHandlers() which has been there since 3.10. Isn't there some Quarkus-specific preinitialization to this?

**Comment by BalusC** [comment]
Ah, it's caused by it being triggered during `ServletContextListener#contextInitialized()` while ServletContext is busy being initialized and the `FacesConfigXmlSingleton` trying to get `ServletContext` from CDI via `Servlets#getContext()` as follows:

```
    public static ServletContext getContext() {
        if (Faces.hasContext()) {
            return Faces.getServletContext();
        }

        BeanManager beanManager = Beans.getManager();

        if (BeansLocal.isActive(beanManager, RequestScoped.class)) {
            return BeansLocal.getInstance(beanManager, ServletContext.class);
        }
        else {
            // #522 For some reason Weld by default searches for the ServletContext in the request scope.
            // But this won't work during e.g. startup. So we need to explicitly search in application scope.
            Bean<ServletContext> bean = BeansLocal.resolve(beanManager, ServletContext.class);
            Context context = beanManager.getContext(ApplicationScoped.class);
            return context.get(bean, beanManager.createCreationalContext(bean));
        }
    }
```
I probably need to look for a different/better way there ...

**Comment by melloware** [comment]
That is what I was suspecting too i was looking through changes between 4.4.1 and 4.5 and this seems like the only change that could have causes this.

**Comment by BalusC** [comment]
According to the stack trace the `if (BeansLocal.isActive(beanManager, RequestScoped.class)) {` appears to be matched. This is unexpected but perhaps not unsurprising as in Quarkus everything is kind of lazy. Wondering if the logic in the else block would have worked for Quarkus? Can you test that?

**Comment by melloware** [comment]
ok let me try a local build of OmniFaces Snapshot and try that.

**Comment by BalusC** [comment]
It should be OK to remove the entire if/else. The code was originally a `return BeansLocal.getInstance(beanManager, ServletContext.class);` but it failed during servlet context init when using Weld. Then an if-else was added with new code in else. But I think the entire if-else can be replaced by solely the code in else. 

```
    public static ServletContext getContext() {
        if (Faces.hasContext()) {
            return Faces.getServletContext();
        }

        var beanManager = Beans.getManager();
        var bean = BeansLocal.resolve(beanManager, ServletContext.class);
        var context = beanManager.getContext(ApplicationScoped.class);
        return context.get(bean, beanManager.createCreationalContext(bean));
    }
```

**Comment by melloware** [comment]
ok will report back!

**Comment by BalusC** [comment]
Currently running local IT tests with changed code as well. Passed in WildFly and GlassFish (both Weld users) TomEE pending ..

**Comment by melloware** [comment]
Hmmm still getting the same error i made the fix locally and built a 4.5.1-SNAPSHOT same stack trace.

**Comment by BalusC** [comment]
Same stack trace even after removing if/else? :o 

Anyway, TomEE passed, so I will publish an actual 4.5.1-SNAPSHOT soon.

**Comment by melloware** [comment]
yes the error is definitely coming from here.

```java
    /**
     * This will register the {@link FacesExceptionFilter} when {@link FullAjaxExceptionHandler} is explicitly registered.
     * This is invoked by {@link ApplicationListener}.
     * @param servletContext The involved servlet context.
     * @since 4.5
     */
    public static void registerFacesExceptionFilterIfNecessary(ServletContext servletContext) {
        if (FacesConfigXml.instance().getExceptionHandlerFactories().stream()
                .noneMatch(FullAjaxExceptionHandlerFactory.class::equals))
        {
            return; // FullAjaxExceptionHandler is not registered.
        }

        if (servletContext.getFilterRegistrations().values().stream()
                .map(FilterRegistration::getClassName)
                .map(Reflection::toClassOrNull).filter(Objects::nonNull)
                .anyMatch(FacesExceptionFilter.class::equals))
        {
            return; // FacesExceptionFilter is already explicitly registered.
        }

        servletContext
            .addFilter(FacesExceptionFilter.class.getName(), FacesExceptionFilter.class)
            .addMappingForUrlPatterns(EnumSet.of(REQUEST), false, "/*");
        logger.log(INFO, FACES_EXCEPTION_FILTER_AUTO_INSTALLED);
    }
```

Which looks new in 4.5?


```
Caused by: java.lang.ExceptionInInitializerError
        at org.omnifaces.config.FacesConfigXml.instance(FacesConfigXml.java:66)
        at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.registerFacesExceptionFilterIfNecessary(FullAjaxExceptionHandler.java:332)
        at org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:95)
        ... 16 more
Caused by: java.lang.IllegalStateException: FacesConfigXml failed to initialize. Perhaps your faces-config.xml contains a typo?
        at org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:109)
        at org.omnifaces.config.FacesConfigXmlSingleton.<clinit>(FacesConfigXmlSingleton.java:60)
        ... 19 more
Caused by: jakarta.enterprise.inject.CreationException: Null contextual instance was produced by a normal scoped synthetic bean: SYNTHETIC bean [class=jakarta.servlet.ServletContext, id=CYpq0iv9Pf0bdpqTn39pTx7xoyM]
        at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.doCreate(Unknown Source)
        at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.create(Unknown Source)
        at jakarta.servlet.ServletContext_CYpq0iv9Pf0bdpqTn39pTx7xoyM_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c20(Unknown Source)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at org.omnifaces.util.Servlets.getContext(Servlets.java:812)
        at org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:99)
        ... 20 more
```

**Comment by BalusC** [comment]
Okay the exception is same but stack trace is different (which is indeed expected). I'll have to look for a way to pass the ServletContext from ApplicationListener to FacesConfigXml.

**Comment by melloware** [comment]
Yep just to confirm if i comment out this line eveyrthing starts up and passes.

```java
FacesViews.addFacesServletMappings(servletContext);
ViewResourceHandler.addFacesServletMappingsIfNecessary(servletContext);
//FullAjaxExceptionHandler.registerFacesExceptionFilterIfNecessary(servletContext);
```

**Comment by BalusC** [comment]
I passed init servlet context via faces context and all IT pass. Please try next snapshot when published.

**Comment by melloware** [comment]
I can confirm 4.5.1-SNAPSHOT works now with Quarkus.

**Comment by BalusC** [comment]
Cool. Will release 4.5.1 soon.

**Comment by BalusC** [comment]
4.5.1 is available now.

Thank you very much for reporting and improving OmniFaces!

**Comment by melloware** [comment]
Thanks for the quick fix!

**Comment by felipelx07** [comment]
Hey dear @melloware i'm still getting this error on version 4.5.1.1 of _**io.quarkiverse.omnifaces:quarkus-omnifaces**_ 
Any suggestion to fix it ?
