### ISSUE TITLE
Exception on startup with 4.5

### ISSUE THREAD

**Issue by OBreidenbach** [omnifaces/omnifaces#862]
After upgrade from 4.4.1 to 4.5.1 i get an ecxeption during startup. 
A comment in the exception-handler-factory element causes the following exception.
As workaround I just moved the comment outside the element.

```html
    ...  
    <exception-handler-factory>
       <!-- comment breaks startup -->
       org.omnifaces.exceptionhandler.FullAjaxExceptionHandlerFactory
    </exception-handler-factory>
    ...  
``` 
```java
Caused by: java.lang.IllegalStateException: OmniFaces failed to initialize! Report an issue to OmniFaces.
	at deployment.intern.war//org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:117)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:219)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
	... 10 more
Caused by: java.lang.ExceptionInInitializerError
	at deployment.intern.war//org.omnifaces.config.FacesConfigXml.instance(FacesConfigXml.java:66)
	at deployment.intern.war//org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.registerFacesExceptionFilterIfNecessary(FullAjaxExceptionHandler.java:332)
	at deployment.intern.war//org.omnifaces.ApplicationListener.contextInitialized(ApplicationListener.java:102)
	... 21 more
Caused by: java.lang.IllegalStateException: FacesConfigXml failed to initialize. Perhaps your faces-config.xml contains a typo?
	at deployment.intern.war//org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:108)
	at deployment.intern.war//org.omnifaces.config.FacesConfigXmlSingleton.<clinit>(FacesConfigXmlSingleton.java:60)
	... 24 more
Caused by: java.lang.IllegalStateException: Cannot load class ''.
	at deployment.intern.war//org.omnifaces.util.Reflection.toClass(Reflection.java:720)
	at deployment.intern.war//org.omnifaces.config.FacesConfigXmlSingleton.parseExceptionHandlerFactories(FacesConfigXmlSingleton.java:216)
	at deployment.intern.war//org.omnifaces.config.FacesConfigXmlSingleton.<init>(FacesConfigXmlSingleton.java:105)
	... 25 more
Caused by: java.lang.ClassNotFoundException: 
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at deployment.intern.war//org.omnifaces.util.Reflection.toClass(Reflection.java:709)
	... 27 more
```

**Comment by BalusC** [comment]
Fixed, thank you very much for reporting and improving OmniFaces!
