### ISSUE TITLE
Silent web socket exceptions in the log keep popping up

### ISSUE THREAD

**Issue by matsandreassen** [omnifaces/omnifaces#867]
I've been using OmniFaces (4.4.1) sockets along with OmniFaces ViewScoped for a while now. I've noticed the following stack traces are logged:

`2024-09-15 17:36:04 [http-nio-8080-exec-4] ERROR o.omnifaces.cdi.push.SocketEndpoint - SocketEndpoint: An exception occurred during processing web socket request.
java.io.EOFException: null
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1293)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1181)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:74)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Unknown Source)
`

Note: We're on Java 21 (Temurin), JSF 4.0 and Tomcat 10.1.(30). I read in your source that you log exceptions when the CloseReason isn't GOING_AWAY, but it would also be useful to log what that code actually is. I'm currently hoping it will soon hit my breakpoint in order to determine this.

**Comment by matsandreassen** [comment]
SocketSessionManager constructs a channelId consisting of the actual _channelId_ and the _session query string._ Is this intentional?

groupEventChannel?d0aa247f-aa7a-40cc-9750-4d4d333ea707

The actual GET URL is **controllerGroupDashboard.xhtml?id=9f0e6302-7742-4549-bd0d-b814426fd4ea**

Is this the correct behaviour?

![image](https://github.com/user-attachments/assets/09bf0c28-004b-4cb2-bf4d-948baec2a3fb)

![image](https://github.com/user-attachments/assets/7e965e47-fd9e-4a06-8f48-4bb6ecbe4717)

**Comment by BalusC** [comment]
> java.io.EOFException: null at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer

This kind of error is comparable to "connection reset by peer" and can be safely ignored in logging: https://stackoverflow.com/q/8658118/

> I read in your source that you log exceptions when the CloseReason isn't GOING_AWAY, but it would also be useful to log what that code actually is.

Agreed. I'll adjust that.

> SocketSessionManager constructs a channelId consisting of the actual channelId and the session query string. Is this intentional?

The "session query string" is actually the unique web socket connection identifier because the web sockets connections are basically collected application wide (so that push can at least reach them form anywhere). Yes, that URL format is intentional, and has nothing to do with the parent page nor HTTP sessions.

**Comment by BalusC** [comment]
It will now be logged as FINE.
